### ISSUE TITLE
System Console unavailable from website if marketplace is down

### ISSUE THREAD

**Issue by gergoradeczki** [mattermost/mattermost#21547] opened 2022-10-28 10:06 UTC
#### Summary

I can't modify system settings when Marketplace is down because System Console shows a blank screen.

![image](https://user-images.githubusercontent.com/4851436/198560127-cbf87299-10dc-4cd7-bb08-9263ea49845e.png)

![image](https://user-images.githubusercontent.com/4851436/198561485-56feb9ea-5f08-4ebe-97a2-9e6912aa93c2.png)

#### Steps to reproduce

- Self hosted
- Mattermost Enterprise Edition
- Mattermost Version: 7.4.0
- Database Schema Version: 93
- Database: mysql
- config.json value `"MarketplaceURL": "https://api.integrations.mattermost.com"`

#### Expected behavior

System Console should be usable while plugin marketplace is down

#### Observed behavior (that appears unintentional) 

![image](https://user-images.githubusercontent.com/4851436/198561108-601cc80a-a53c-445f-bac5-6e1826ca89b6.png)

**Comment by amyblais** [comment] 2022-10-28 13:37
Opened: https://mattermost.atlassian.net/browse/MM-48013.

**Comment by hanzei** [comment] 2022-10-28 14:59
@gergoradeczki Does disabling the Marketplace (by setting`EnableMarketplace` to `false`) fix the system console?

**Comment by gergoradeczki** [comment] 2022-10-28 15:06
@hanzei I tried it, and System Console is available after disabling Marketplace through config.json
![image](https://user-images.githubusercontent.com/4851436/198668228-74ed1d4d-2e8a-4295-b0c8-fe889850319f.png)

**Comment by gergoradeczki** [comment] 2022-10-28 15:08
Nevermind, Marketplace is up, so I can't really reproduce this _(maybe setting a bad URL for marketplace might be good enough)_

**Comment by gergoradeczki** [comment] 2022-10-28 15:21
I tried to set `MarketplaceURL` to a bad one _(to simulate an unavailable service eg. `https://apis.integrations.mattermost.com`)_, and System Console is available even though I got the "Error connecting to..." error message.

It's worth noting that plugins did get loaded this time. I did not modify my plugins. In the picture above this section was empty.
![image](https://user-images.githubusercontent.com/4851436/198673674-b867e550-d73d-446c-82d6-d0d888c39de9.png)

**Comment by hanzei** [comment] 2022-10-28 15:25
Hm, I have trouble reproducing your issue. Setting `MarketplaceURL` to a "bad" one doesn't crash the system console. I get the same behavior as you.

On your first screenshot it can be seen that `GET /api/v4/config` failed with a 403. Do you see anything related to this failed request in the server logs? Maybe this failing request is the root cause of the blank system console, not the Marketplace.

**Comment by amyblais** [comment] 2023-11-17 13:29
Closing for now as we haven't been able to reproduce this,

**Closed by amyblais** 2023-11-17 13:29 UTC
Labels: Bug Report/Open
