### ISSUE TITLE
Red banner "A JavaScript error has occurred" appears, when press ESC button

### ISSUE THREAD

**Issue by yukpun** [mattermost/mattermost#23802] opened 2023-06-20 09:02 UTC
#### Summary
When press ESC button in any place of Mattermost client, red banner will appear with "Javascript error"

#### Steps to reproduce
Press ESC

#### Expected behavior
No Javascript errors

#### Observed behavior (that appears unintentional) 
<img width="1512" alt="SCR-20230620-kwbj" src="https://github.com/mattermost/mattermost/assets/23419090/14bda632-011e-4cb0-af1b-8dda526d5d3b">

<img width="798" alt="SCR-20230620-kvvt" src="https://github.com/mattermost/mattermost/assets/23419090/dfe35562-c470-4fc2-9191-d7188bc43db7">

**Macos client 5.4.0 commit 420c63d**

**Comment by amyblais** [comment] 2023-06-20 12:45
Hi @yukpun,
1. Does this only happen on the desktop app or does it also happen on webapp?
2. What Mattermost server version are you on?
3. What MacOS version are you on?
4. Do you see errors in the Mattermost server logs?

**Comment by yukpun** [comment] 2023-06-20 13:50
1. Both Desktop app (dmg and from AppStore) and Web
2. Version 5.4.0 (52580796761)
3. 13.3.1 (22E261). I want to add, that this behavoir is on Windows clients too
4. A don't have access to server logs

**Comment by amyblais** [comment] 2023-06-20 13:51
2. You can find the server version from Main Menu > About.

![image](https://github.com/mattermost/mattermost/assets/29708087/6767dc69-e08f-4edd-9b15-68fe7dd795d7)

**Comment by yukpun** [comment] 2023-06-20 13:53
Mattermost Enterprise Edition

Mattermost Version: 7.10.0
Database Schema Version: 105

**Comment by amyblais** [comment] 2023-06-20 14:29
Opened https://mattermost.atlassian.net/browse/MM-53266.

**Comment by HarshPanchal26** [comment] 2023-06-21 16:33
Hey Can I help in this @yukpun  ?

**Comment by amyblais** [comment] 2023-06-27 14:19
@yukpun The Jira ticket was closed as we couldn't reproduce this. Are there any additional reproduction steps that you can help share?

**Comment by amyblais** [comment] 2023-07-27 13:39
Closing as we haven't received a response for a while,

**Comment by tocic** [comment] 2023-08-12 07:06
Please consider reoping this as it's easily reproduced in `Windows 10 19045.3324` with `Mattermost Desktop 5.2.2` for me (I'm just pressing <kbd>ESC</kbd>):

![bug](https://github.com/mattermost/mattermost/assets/22129543/18d946bd-a301-456a-a962-4c33099c3593)

**Comment by amyblais** [comment] 2024-07-26 12:10
@tocic We have been unable to reproduce this. Would you be open to upgrading your server version and desktop app version to the latest?

**Comment by tocic** [comment] 2024-07-27 04:17
Unfortunately, I can't control the server version installed at my work (9.5.1.7877*). I've updated my desktop version from [5.7.0](https://archlinux.org/packages/extra/x86_64/mattermost-desktop) to [5.8.1](https://aur.archlinux.org/packages/mattermost-desktop-bin), but the issue is still reproducible on Linux (haven't tested on Windows).

**Comment by amyblais** [comment] 2024-07-30 18:50
@tocic Are you able to reproduce the issue on our community server https://community.mattermost.com/?

**Comment by tocic** [comment] 2024-07-31 04:20
I can't reproduce the issue on that server.

**Comment by amyblais** [comment] 2024-09-09 22:28
Closing for now as we haven't been able to reproduce this internally.

**Closed by amyblais** 2024-09-09 22:28 UTC
