### ISSUE TITLE
Updating "Full name" via browser on the community server causes `Invalid or missing password in request body` error

### ISSUE THREAD

**Issue by jugmac00** [mattermost/mattermost#23770] opened 2023-06-16 06:45 UTC
#### Summary
Updating "Full name" via browser on the community server causes `Invalid or missing password in request body` error

#### Steps to reproduce
- go to https://community.mattermost.com/
- click profile settings
- click on "edit" next to full name
- update first name with "Jürgen", last name with "Gmach"
- hit save
- error

#### Expected behavior
Name should be updated.

#### Observed behavior (that appears unintentional) 
error message, see above

#### Possible fixes
No fix, but a very similar issue was already reported back then and closed, see https://github.com/mattermost/mattermost/issues/21499

**Comment by amyblais** [comment] 2023-06-16 13:55
Opened https://mattermost.atlassian.net/browse/MM-53216.

**Comment by crspeller** [comment] 2023-06-19 18:38
@jugmac00 Are you still seeing the issue? I can't reproduce on community right now. 
If you are, could you post a sanitized version of the request and response body using the browser dev tools? It would help in understanding what is going on here.

**Comment by amyblais** [comment] 2023-06-19 18:44
@crspeller I'm able to reproduce it with a test account using normal email + password login.

**Comment by crspeller** [comment] 2023-06-19 18:46
@amyblais I am unable to under the same conditions. Could you point the sanitized request and response body and browser info.

**Comment by amyblais** [comment] 2023-06-19 19:07
Chrome v114.0.5735.133 (Official Build) (arm64)

<img width="545" alt="Screenshot at Jun 19 15-06-51" src="https://github.com/mattermost/mattermost/assets/29708087/1b263f89-104a-47b1-bb0e-6f4399581646">

**Comment by jugmac00** [comment] 2023-06-21 08:18
@crspeller The issue has been fixed for me - thanks.

I am not closing it, as @amyblais still experiences issue.

**Comment by amyblais** [comment] 2023-06-21 12:21
I'm still reproducing this. We can close this issue and track this via the Jira ticket.

**Closed by amyblais** 2023-06-21 12:21 UTC
Labels: Bug Report/Open
