### ISSUE TITLE
Crash when opening Threads with latex formula (iOS)

### ISSUE THREAD

**Issue by kc9jud** [mattermost/mattermost#24982] opened 2023-10-13 16:37 UTC
Opening "Threads" from the sidebar leads to a crash:
```

2023/10/13 11:32:25:202 WARNING Handling Javascript error Invariant Violation: View config getter callback for component `span` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This error is located at:
    in span
    in LatexInline
    in RemoveMarkdown
    in RCTText
    in render
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in TouchableHighlight
    in Unknown
    in Thread
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in VirtualizedListCellContextProvider
    in CellRenderer
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in ScrollView
    in VirtualizedListContextProvider
    in VirtualizedList
    in FlatList
    in ThreadsList
    in ConcreteWithObservablesComponent
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in RNCSafeAreaView
    in Unknown
    in GlobalThreads
    in ConcreteWithObservablesComponent
    in Unknown
    in ThemeProvider
    in ConcreteWithObservablesComponent
    in ServerUrlProvider
    in IntlProvider
    in UserLocaleProvider
    in ConcreteWithObservablesComponent
    in DatabaseProvider
    in ServerDatabaseComponent
    in Provider
    in EmmProvider
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in SafeAreaInsets
    in RCTView
    in Unknown
    in GestureHandlerRootView
    in gestureHoc
    in WrappedComponent
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes 0
2023/10/13 11:32:25:202 ERROR Invariant Violation: View config getter callback for component `span` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This error is located at:
    in span
    in LatexInline
    in RemoveMarkdown
    in RCTText
    in render
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in TouchableHighlight
    in Unknown
    in Thread
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in VirtualizedListCellContextProvider
    in CellRenderer
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in ScrollView
    in VirtualizedListContextProvider
    in VirtualizedList
    in FlatList
    in ThreadsList
    in ConcreteWithObservablesComponent
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in RNCSafeAreaView
    in Unknown
    in GlobalThreads
    in ConcreteWithObservablesComponent
    in Unknown
    in ThemeProvider
    in ConcreteWithObservablesComponent
    in ServerUrlProvider
    in IntlProvider
    in UserLocaleProvider
    in ConcreteWithObservablesComponent
    in DatabaseProvider
    in ServerDatabaseComponent
    in Provider
    in EmmProvider
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in SafeAreaInsets
    in RCTView
    in Unknown
    in GestureHandlerRootView
    in gestureHoc
    in WrappedComponent
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes
2023/10/13 11:32:25:203 WARNING Handling Javascript error Invariant Violation: View config getter callback for component `span` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This error is located at:
    in span
    in LatexInline
    in RemoveMarkdown
    in RCTText
    in render
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in TouchableHighlight
    in Unknown
    in Thread
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in VirtualizedListCellContextProvider
    in CellRenderer
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in ScrollView
    in VirtualizedListContextProvider
    in VirtualizedList
    in FlatList
    in ThreadsList
    in ConcreteWithObservablesComponent
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in RNCSafeAreaView
    in Unknown
    in GlobalThreads
    in ConcreteWithObservablesComponent
    in Unknown
    in ThemeProvider
    in ConcreteWithObservablesComponent
    in ServerUrlProvider
    in IntlProvider
    in UserLocaleProvider
    in ConcreteWithObservablesComponent
    in DatabaseProvider
    in ServerDatabaseComponent
    in Provider
    in EmmProvider
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in SafeAreaInsets
    in RCTView
    in Unknown
    in GestureHandlerRootView
    in gestureHoc
    in WrappedComponent
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes 0
2023/10/13 11:32:25:203 ERROR Invariant Violation: View config getter callback for component `span` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This error is located at:
    in span
    in LatexInline
    in RemoveMarkdown
    in RCTText
    in render
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in TouchableHighlight
    in Unknown
    in Thread
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in VirtualizedListCellContextProvider
    in CellRenderer
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in ScrollView
    in VirtualizedListContextProvider
    in VirtualizedList
    in FlatList
    in ThreadsList
    in ConcreteWithObservablesComponent
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in RNCSafeAreaView
    in Unknown
    in GlobalThreads
    in ConcreteWithObservablesComponent
    in Unknown
    in ThemeProvider
    in ConcreteWithObservablesComponent
    in ServerUrlProvider
    in IntlProvider
    in UserLocaleProvider
    in ConcreteWithObservablesComponent
    in DatabaseProvider
    in ServerDatabaseComponent
    in Provider
    in EmmProvider
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in SafeAreaInsets
    in RCTView
    in Unknown
    in GestureHandlerRootView
    in gestureHoc
    in WrappedComponent
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes
2023/10/13 11:32:25:206 WARNING Handling Javascript error {
    componentStack = "\n    in span\n    in LatexInline\n    in RemoveMarkdown\n    in RCTText\n    in render\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in TouchableHighlight\n    in Unknown\n    in Thread\n    in ConcreteWithObservablesComponent\n    in Unknown\n    in RCTView\n    in Unknown\n    in VirtualizedListCellContextProvider\n    in CellRenderer\n    in RCTScrollContentView\n    in RCTScrollView\n    in ScrollView\n    in ScrollView\n    in VirtualizedListContextProvider\n    in VirtualizedList\n    in FlatList\n    in ThreadsList\n    in ConcreteWithObservablesComponent\n    in ConcreteWithObservablesComponent\n    in Unknown\n    in RCTView\n    in Unknown\n    in RNCSafeAreaView\n    in Unknown\n    in GlobalThreads\n    in ConcreteWithObservablesComponent\n    in Unknown\n    in ThemeProvider\n    in ConcreteWithObservablesComponent\n    in ServerUrlProvider\n    in IntlProvider\n    in UserLocaleProvider\n    in ConcreteWithObservablesComponent\n    in DatabaseProvider\n    in ServerDatabaseComponent\n    in Provider\n    in EmmProvider\n    in RNCSafeAreaProvider\n    in SafeAreaProvider\n    in SafeAreaInsets\n    in RCTView\n    in Unknown\n    in GestureHandlerRootView\n    in gestureHoc\n    in WrappedComponent\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in AppContainer";
    framesToPop = 1;
    isComponentError = 1;
    jsEngine = hermes;
    name = "Invariant Violation";
} 1
```

Application info:
```
Current User Id: c1kc6qfwm3dk8jqbnuyo1a5agy
Current Team Id: ihhmpw5r37robps4hzh4wzaojo
Server Version: 8.1.1 (Build 8.1.1)
App Version: 2.8.2 (Build 488)
App Platform: ios
Device Model: iPhone14,6
```

**Comment by kc9jud** [comment] 2023-10-18 05:14
Possibly related: all LaTeX is now failing to render on mobile, but works fine on both desktop and browser (including mobile Safari).

**Comment by jannikbertram** [comment] 2023-10-18 09:00
> Possibly related: all inline LaTeX is now failing to render on mobile, but works fine on both desktop and browser (including mobile Safari). Display mode (i.e. `latex` code blocks) still render correctly.

I can confirm that
<img width="368" alt="image" src="https://github.com/mattermost/mattermost/assets/17082165/1bad9e12-49a3-4d58-875e-53d3080e5abb">

**Comment by jannikbertram** [comment] 2023-10-18 09:05
I can also reproduce **an error** when clicking on "Threads", but not the error you posted @kc9jud.

This is the error I get:
```
 ERROR  TypeError: Cannot add new property 'data-latex-code'

This error is located at:
    in LatexInline (created by RemoveMarkdown)
    in RemoveMarkdown (created by Thread)
    in RCTText (created by Text)
    in render (created by Thread)
    in RCTView (created by View)
    in View (created by Thread)
    in RCTView (created by View)
    in View (created by Thread)
    in RCTView (created by View)
    in View (created by TouchableHighlight)
    in TouchableHighlight (created by TouchableHighlight)
    in TouchableHighlight (created by Thread)
    in Thread (created by withObservables[] { post, thread, channel, author })
    in withObservables[] { post, thread, channel, author }
    in Unknown (created by CellRenderer)
    in RCTView (created by View)
    in View (created by CellRenderer)
    in VirtualizedListCellContextProvider (created by CellRenderer)
    in CellRenderer (created by VirtualizedList)
    in RCTScrollContentView (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by VirtualizedList)
    in VirtualizedListContextProvider (created by VirtualizedList)
    in VirtualizedList (created by FlatList)
    in FlatList (created by ThreadsList)
    in ThreadsList (created by withObservables[tab,teamId] { unreadsCount, teammateNameDisplay, threads })
    in withObservables[tab,teamId] { unreadsCount, teammateNameDisplay, threads } (created by withObservables[] { teamId })
    in withObservables[] { teamId }
    in Unknown (created by GlobalThreads)
    in RCTView (created by View)
    in View (created by GlobalThreads)
    in RNCSafeAreaView
    in Unknown (created by GlobalThreads)
    in GlobalThreads (created by withObservables[] { globalThreadsTab })
    in withObservables[] { globalThreadsTab }
    in Unknown (created by ServerDatabaseComponent)
    in ThemeProvider (created by withObservables[] { currentTeamId, themes })
    in withObservables[] { currentTeamId, themes } (created by ServerDatabaseComponent)
    in ServerUrlProvider (created by ServerDatabaseComponent)
    in IntlProvider (created by UserLocaleProvider)
    in UserLocaleProvider (created by withObservables[] { locale })
    in withObservables[] { locale } (created by ServerDatabaseComponent)
    in DatabaseProvider (created by ServerDatabaseComponent)
    in ServerDatabaseComponent (created by EmmProvider)
    in Provider (created by EmmProvider)
    in EmmProvider (created by SafeAreaInsets)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsets)
    in SafeAreaInsets (created by gestureHoc)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by gestureHoc)
    in gestureHoc (created by WrappedComponent)
    in WrappedComponent
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in GlobalThreads(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot add new property 'data-latex-code'

This error is located at:
    in LatexInline (created by RemoveMarkdown)
    in RemoveMarkdown (created by Thread)
    in RCTText (created by Text)
    in render (created by Thread)
    in RCTView (created by View)
    in View (created by Thread)
    in RCTView (created by View)
    in View (created by Thread)
    in RCTView (created by View)
    in View (created by TouchableHighlight)
    in TouchableHighlight (created by TouchableHighlight)
    in TouchableHighlight (created by Thread)
    in Thread (created by withObservables[] { post, thread, channel, author })
    in withObservables[] { post, thread, channel, author }
    in Unknown (created by CellRenderer)
    in RCTView (created by View)
    in View (created by CellRenderer)
    in VirtualizedListCellContextProvider (created by CellRenderer)
    in CellRenderer (created by VirtualizedList)
    in RCTScrollContentView (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by VirtualizedList)
    in VirtualizedListContextProvider (created by VirtualizedList)
    in VirtualizedList (created by FlatList)
    in FlatList (created by ThreadsList)
    in ThreadsList (created by withObservables[tab,teamId] { unreadsCount, teammateNameDisplay, threads })
    in withObservables[tab,teamId] { unreadsCount, teammateNameDisplay, threads } (created by withObservables[] { teamId })
    in withObservables[] { teamId }
    in Unknown (created by GlobalThreads)
    in RCTView (created by View)
    in View (created by GlobalThreads)
    in RNCSafeAreaView
    in Unknown (created by GlobalThreads)
    in GlobalThreads (created by withObservables[] { globalThreadsTab })
    in withObservables[] { globalThreadsTab }
    in Unknown (created by ServerDatabaseComponent)
    in ThemeProvider (created by withObservables[] { currentTeamId, themes })
    in withObservables[] { currentTeamId, themes } (created by ServerDatabaseComponent)
    in ServerUrlProvider (created by ServerDatabaseComponent)
    in IntlProvider (created by UserLocaleProvider)
    in UserLocaleProvider (created by withObservables[] { locale })
    in withObservables[] { locale } (created by ServerDatabaseComponent)
    in DatabaseProvider (created by ServerDatabaseComponent)
    in ServerDatabaseComponent (created by EmmProvider)
    in Provider (created by EmmProvider)
    in EmmProvider (created by SafeAreaInsets)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsets)
    in SafeAreaInsets (created by gestureHoc)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by gestureHoc)
    in gestureHoc (created by WrappedComponent)
    in WrappedComponent
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in GlobalThreads(RootComponent), js engine: hermes
```

I'm using the latest versions of the server and mobile code (possibly a reason why the error is not the same).

It seems to be related to `LatexInline` from [commonmark-react-renderer](https://github.com/mattermost/commonmark-react-renderer). Will further investigate this, perhaps by using older versions of the commonmark renderer. 

Please let me know if you have other ideas how to debug this

**Comment by kc9jud** [comment] 2023-10-18 21:01
This is a relatively recent problem, within the last two months or so... it may be easiest to bisect and find when the break happened.

**Comment by jannikbertram** [comment] 2023-10-19 14:20
Thanks for the hint. I found out that version 2.7.0 was still working and the bug was introduced in 2.8.0. Now it should be easier to pinpoint which change caused the issue.

On a side note, messages in the "Threads" view are rendered differently than in the "Channel" view. IMO, it would be more consistent and robust if both views use the same component to render the message. That might be something for later though, I'm gonna focus on fixing the bug first so the app doesn't crash

**Comment by jannikbertram** [comment] 2023-10-20 11:09
Finally found the problem and proposed a fix for it 🙌

**Comment by jannikbertram** [comment] 2023-10-24 20:17
@kc9jud can I get someone to look at the PR? Would be nice to get that merged / approved before hacktoberfest is over :)

**Comment by hmhealey** [comment] 2023-10-25 21:34
Reopening this since we still need to update the mobile app to use the new version of commonmark-react-renderer

**Closed** 2023-10-31 16:33 UTC
Labels: Hacktoberfest, Help Wanted
