### ISSUE TITLE
Failed to set up a develop environment in Ubuntu and MacOS

### ISSUE THREAD

**Issue by 1622145167** [mattermost/mattermost#24155] opened 2023-07-28 15:12 UTC
#### Summary
Ubuntu version: 22.04 LTS
When I try to set up a dev env on a virtual ubuntu machine, I have done all the tasks on this [page](https://developers.mattermost.com/contribute/developer-setup/), but when running `make run`, the `webapp` can't be built successfully. The `server` application is built and running.

#### Expected behavior
The environment is set up successfully.

### Parts of errors
```
[webapp] ERROR in ./src/components/gif_picker/static/search_end.png

 [webapp] Module build failed (from ../node_modules/image-webpack-loader/index.js):

 [webapp] Error: Cannot find module 'imagemin-gifsicle'

 [webapp] Require stack:

 [webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/image-webpack-loader/index.js

 [webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/webpack/lib/ProgressPlugin.js

 [webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/webpack/lib/index.js

 [webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/webpack-cli/lib/webpack-cli.js

 [webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/webpack-cli/lib/bootstrap.js

 [webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/webpack-cli/bin/cli.js

 [webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/webpack/bin/webpack.js

 [webapp]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)

 [webapp]     at Module._load (node:internal/modules/cjs/loader:922:27)

 [webapp]     at Module.require (node:internal/modules/cjs/loader:1143:19)

 [webapp]     at require (node:internal/modules/cjs/helpers:110:18)

 [webapp]     at module.exports (/home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/image-webpack-loader/index.js:72:20)
```

```
[webapp] ERROR in ./src/fonts/Metropolis-Light.woff

[webapp] Module build failed (from ../node_modules/image-webpack-loader/index.js):

[webapp] Error: Cannot find module 'imagemin-gifsicle'

[webapp] Require stack:

[webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/image-webpack-loader/index.js

[webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/webpack/lib/ProgressPlugin.js

[webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/webpack/lib/index.js

[webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/webpack-cli/lib/webpack-cli.js

[webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/webpack-cli/lib/bootstrap.js

[webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/webpack-cli/bin/cli.js

[webapp] - /home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/webpack/bin/webpack.js

[webapp]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)

[webapp]     at Module._load (node:internal/modules/cjs/loader:922:27)

[webapp]     at Module.require (node:internal/modules/cjs/loader:1143:19)

[webapp]     at require (node:internal/modules/cjs/helpers:110:18)

[webapp]     at module.exports (/home/ubuntu/Desktop/mattermost-8.0.0/webapp/node_modules/image-webpack-loader/index.js:72:20)
```

**Comment by amyblais** [comment] 2023-07-28 16:17
This sounds similar to https://github.com/mattermost/mattermost/issues/24120, so I'll close this as a duplicate. Let me know if I'm incorrect,

**Comment by 1622145167** [comment] 2023-07-29 02:43
I think the problem in #24120 isn't similar to mine. So the issue should be opened again. If you need more information or logs, please tell me.

**Comment by amyblais** [comment] 2023-07-31 13:32
Sounds good 👍 Posting about this either on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or [Developers channel](https://community.mattermost.com/core/channels/developers) makes sense and one of our devs or other community members will likely be able to help troubleshoot this question.

**Comment by 1622145167** [comment] 2023-08-03 13:47
> Now someone has the same problem too. And we are thinking how to deal with it. If one of community members comes to help me, I would be immensely grateful!

**Comment by 1622145167** [comment] 2023-08-03 14:02
> @1622145167 Sharing the solution in the other Github issue: [#24120 (comment)](https://github.com/mattermost/mattermost/issues/24120#issuecomment-1663434347). It may not be the same solution for you, just sharing in case it's helpful.

Thanks. Yesterday I found a member stuck in the same problem. I tried again and again to run `make run` in `webapp` but failed.

**Comment by amyblais** [comment] 2023-08-03 14:55
Opened https://mattermost.atlassian.net/browse/MM-53919 as the solution in the other Github issue didn't help here.

**Comment by 1622145167** [comment] 2023-08-10 13:08
> Does your Mac have an M1/M2 processor or an older x86 one? And if it's M1/M2, do you have Rosetta installed?
> 
> Many of those `imagemin` dependencies have native dependencies which sometimes need to be installed manually

It is x86. When run `npm i imagemin-gifsicle` and `npm i imagemin-mozjpeg`, it could run again!

**Comment by 1622145167** [comment] 2023-08-10 13:09
It seems that the project can't run on a virtual machine, both macOS and Ubuntu.

**Comment by hmhealey** [comment] 2023-08-15 17:50
Okay, so it's a different issue than the other one we've seen recently since that was specifically on ARM. That's good to hear that manually installing those fixed the issue though.

Which versions of Node and NPM are you using? Perhaps the error is caused by one of those being a different version because we're behind on the versions of both of those. For reference, the versions we use are:
```
harrison-mm:webapp harrison $ node --version
v16.10.0
harrison-mm:webapp harrison $ npm --version
7.24.0
```

**Comment by 1622145167** [comment] 2023-08-24 02:44
> Okay, so it's a different issue than the other one we've seen recently since that was specifically on ARM. That's good to hear that manually installing those fixed the issue though.
> 
> Which versions of Node and NPM are you using? Perhaps the error is caused by one of those being a different version because we're behind on the versions of both of those. For reference, the versions we use are:
> 
> ```
> harrison-mm:webapp harrison $ node --version
> v16.10.0
> harrison-mm:webapp harrison $ npm --version
> 7.24.0
> ```

I'm using the latest version.

**Comment by hmhealey** [comment] 2023-08-30 13:40
Hmm, that's very strange. Well, I don't think there's any harm in adding those explicitly to our dependencies since they're already dependencies-of-dependencies.

Would you mind submitting a PR to add those? You might need to update to the latest master before you do that though since we actually just updated our Node/NPM versions a couple days ago, but that shouldn't be too hard if you're using NVM to change versions

**Closed** 2024-02-06 22:04 UTC
Labels: Bug Report/Open
