### ISSUE TITLE
[Borwser client] Answer / reaction buttons do not work ; wrong button gets highlighted

### ISSUE THREAD

**Issue by ysalmon** [mattermost/mattermost#25392] opened 2023-11-09 12:09 UTC
#### Summary
Clicking one of the button in the answer/react interface sometimes does not produce any meaningful result.

#### Steps to reproduce
Hover over a message and click one the buttons.
![Screenshot_20231109_130211](https://github.com/mattermost/mattermost/assets/536850/0592117a-7dff-4ad0-b6e9-2c03a4d222e2)

Version 8.0.1 from Arch Linux, says my admin.

Browser has been various versions of Firefox, currently 119.0.1 (64 bits), under KUbuntu 22.04.

#### Expected behavior
Clicking a button should briefly highlight it and perform the corresponding action.

#### Observed behavior (that appears unintentional) 
Clicking a button briefly highlights the button to its immediate left and seems to perform no action.

This bug triggers in seemingly random circumstances. When it does, it will prevent effective usage of the interface, until, suddenly, it works again.

**Comment by amyblais** [comment] 2023-11-09 15:52
Hi @ysalmon, I wasn't able to reproduce this just now. Are you able to reproduce this on our community server https://community.mattermost.com/?

**Comment by ysalmon** [comment] 2023-11-09 17:39
I will try it  — as the problem seems to occur on some occasions only, it may take a while before I can draw a negative conclusion.

**Comment by ysalmon** [comment] 2023-11-09 20:18
So, it was faster than expected : yes, I reproduced this on the community server, although only briefly.

More precisely : I saw it happening with the instance I am using with my colleagues, so I switched to the tab of the community server (I had left it open since earlier), and it happened twice in a row there. Then it worked again, and in my "usual" instance (I had not closed the tab either), it worked too…

**Comment by amyblais** [comment] 2023-11-09 20:22
Thanks, opened https://mattermost.atlassian.net/browse/MM-55414.

**Comment by hmhealey** [comment] 2023-11-13 18:02
Hi @ysalmon. When this happens, does it seem like the UI is lagging, or does it seem like it might be a networking issue? I'm trying to get a better idea about what might be happening here

**Comment by ysalmon** [comment] 2023-11-14 09:12
The UI is not lagging when this happens (I have never had the UI lag on any of my computers). The UI is other wise working properly and responsively : I can change channel, write messages and send them. I cannot use the answer feature, because clicking on the "answer arrow" highlights the bookmark icon instead.

**Comment by hmhealey** [comment] 2023-11-16 21:21
Interesting. I haven't seen that myself, and I use Firefox as well but on Mac. I don't think OS should matter since MM's a web app. Have you seen this happen in any other browsers or on a different machine? That'd help figure out if the OS/browser is related.

Since we haven't gotten any other reports of this and you're seeing it on both community and your server, I'm thinking that there's something special about your browser that might be impacting this. Do you have any extensions that might be adding stuff to the page when MM is open?

Alternatively, if your browser isn't at a zoom level of 100%, that shouldn't normally cause issues, but it's caused issues in the past, so I wouldn't rule that out

**Comment by ysalmon** [comment] 2023-11-24 17:08
I do have a 115% zoom setting. However, right now the problem is happening (with the second button to the left of the clicked button being highlighted), so, having you suggestion in mind, I reset that to 100% but it did not solve the problem.

I will try to disable extensions like privacybadger and ublock for the mattermost instance I am using to see if it improves things.

**Comment by ysalmon** [comment] 2023-12-18 15:16
Experiencing the problem again today with privacy extensions disabled for the relevant domain.

**Comment by amyblais** [comment] 2024-09-06 17:49
Closing for now as we haven't been able to reproduce this,

**Closed by amyblais** 2024-09-06 17:49 UTC
Labels: Bug Report/Open
