### ISSUE TITLE
Stuck notifications when using multiple teams

### ISSUE THREAD

**Issue by agusl88** [mattermost/mattermost#16206] opened 2020-11-03 22:50 UTC
#### Summary
When using multiple teams, we are getting "stuck notifications" that can't be cleared. Notifications seems to be stuck server-side because it happens with all clients, and the situation is present for many users, not just one. 

There seems to be always 1 stuck notification per team, because after reading the regular notifications, the unread count is always 1.

Currently my server is on v5.25.5, but this was happening with the previous LTS version (
5.19).

#### Steps to reproduce
I'm not 100% sure these steps will reproduce the error, but this is what i've done in each case where a new team ended up with a stuck notification"

1 - Create a new team (it only started to happend after i had more than one team in the server)
2 - Add people to the team
3 - Rename the default "Town square" channel

#### Expected behavior
No stuck notificaitons

#### Observed behavior (that appears unintentional) 
[https://imgur.com/hu9c9O1](https://imgur.com/hu9c9O1). 

#### Possible fixes
Haven't found a workaround yet.

**Comment by amyblais** [comment] 2020-11-04 14:25
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-30269

**Comment by isacikgoz** [comment] 2020-11-19 14:52
Hey @agusl88 thanks for reporting this! However, I am having issues while trying to reproduce this bug. Can you please confirm the reproduction steps? Maybe a specific order triggered this in your case? Also the online/offline member statuses and their notifications settings would help a lot.

**Comment by agusl88** [comment] 2020-11-19 17:46
Hi, let me try to reproduce it again so i can provide a more accurate steps. For what is worth, it never happended instantly after creating the channel, notifcations always endedup getting stuck after a few hours/days when people started to use the new team, so is very likely that there is something more involved besides just renaming the default channel.

**Comment by agusl88** [comment] 2020-11-24 18:29
I manage to reproduce the problem again.

1 - Create a secondary team
2 - Added one other person to it
3 - At this point we started sending messages to the channel, doing @ mentions, sending direct messages, switching back and forth in the UI beetwen teams, and renaming the channel several times.

After a few tries, the other user i added in step 2 got a stuck notification, i didn't. Sorry i can't be more specific but  the problem seems to be related to notifications about @mentions and renaming the default channel.

Sceenshoots: https://imgur.com/4NmSouq

**Comment by isacikgoz** [comment] 2020-11-29 21:16
Thanks for helping with this @agusl88! It is much appreciated!! However, I'm still unable to reproduce this on `v.5.25.5` and also on `v.19.3`. I will ask for another colleague of mine to see if they can observer this.

**Comment by thystra** [comment] 2020-12-01 02:22
I have Mattermost MYSQL Version 5.29 and now have stuck notifications as well.  I have several channels in a team (on a server with multiple teams) that continuously appear as unread on the android client and the windows app.  Reading the channels clears the indication, but after a bit it comes back and shows as unread (bold) in the client.  No new messages were posted to the channels in the intervening time.  

Closing the app completely and reopening it causes the session to be expired and the channels remain unread.

**Comment by discostur** [comment] 2020-12-04 20:28
having the same issue like @thystra - just upgraded mattermost from `5.27.0` to `5.29.1`. The issue did not appear in the old ver

**Comment by discostur** [comment] 2020-12-04 20:35
@isacikgoz in the mattermost log i can see the error:
```
{"level":"error","ts":1607113861.4809077,"caller":"mlog/log.go:229","msg":"Unable to update the last viewed at time.","path":"/api/v4/channels/members/me/view","request_id":"qgfyuk6k778ytd3xknz3ehde1y","ip_addr":"192.168.xxx","user_id":"1aukw8gw3fbzinbz88erkio7ey","method":"POST","err_where":"MarkChannelsAsViewed","http_code":500,"err_details":"failed to fetch threads: Error 1267: Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='"}
``

**Comment by MrOffline77** [comment] 2020-12-04 20:36
same problem here.

**Comment by discostur** [comment] 2020-12-04 20:42
@isacikgoz @amyblais i also the the following error:
```
{"level":"warn","ts":1607110575.0874128,"caller":"app/notification.go:272","msg":"Failed to update mention count","post_id":"u8a4b4xfbfyitm1ge6fecf1dmw","channel_id":"f9yqirfsa3ba9b8treqzp5dtga","error":"SendNotifications: Unable to increment the mention count., failed to fetch threads: Error 1267: Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='"}
```

**Comment by amyblais** [comment] 2020-12-04 21:47
Thanks, updated the ticket with the errors.

**Comment by discostur** [comment] 2020-12-07 08:38
@amyblais @isacikgoz it seems to be a problem with the database collations; i just check my default database collation:

```
mysql> show variables like "collation_database";
+--------------------+--------------------+
| Variable_name      | Value              |
+--------------------+--------------------+
| collation_database | utf8mb4_0900_ai_ci |
+--------------------+--------------------+
```

and i checked my mattermost tables:

```
mysql> SELECT table_name, table_collation FROM information_schema.tables WHERE table_schema = 'mattermost';
+------------------------+--------------------+
| TABLE_NAME             | TABLE_COLLATION    |
+------------------------+--------------------+
| Audits                 | utf8mb4_general_ci |
| Bots                   | utf8mb4_general_ci |
| ChannelMemberHistory   | utf8mb4_general_ci |
| ChannelMembers         | utf8mb4_general_ci |
| Channels               | utf8mb4_general_ci |
| ClusterDiscovery       | utf8mb4_general_ci |
| CommandWebhooks        | utf8mb4_general_ci |
| Commands               | utf8mb4_general_ci |
| Compliances            | utf8mb4_general_ci |
| Emoji                  | utf8mb4_general_ci |
| FileInfo               | utf8mb4_general_ci |
| GroupChannels          | utf8mb4_general_ci |
| GroupMembers           | utf8mb4_general_ci |
| GroupTeams             | utf8mb4_general_ci |
| IncomingWebhooks       | utf8mb4_general_ci |
| Jobs                   | utf8mb4_general_ci |
| Licenses               | utf8mb4_general_ci |
| LinkMetadata           | utf8mb4_general_ci |
| OAuthAccessData        | utf8mb4_general_ci |
| OAuthApps              | utf8mb4_general_ci |
| OAuthAuthData          | utf8mb4_general_ci |
| OutgoingWebhooks       | utf8mb4_general_ci |
| PluginKeyValueStore    | utf8mb4_general_ci |
| Posts                  | utf8mb4_general_ci |
| Preferences            | utf8mb4_general_ci |
| ProductNoticeViewState | utf8mb4_0900_ai_ci |
| PublicChannels         | utf8mb4_general_ci |
| Reactions              | utf8mb4_general_ci |
| Roles                  | utf8mb4_general_ci |
| Schemes                | utf8mb4_general_ci |
| Sessions               | utf8mb4_general_ci |
| SidebarCategories      | utf8mb4_0900_ai_ci |
| SidebarChannels        | utf8mb4_0900_ai_ci |
| Status                 | utf8mb4_general_ci |
| Systems                | utf8mb4_general_ci |
| TeamMembers            | utf8mb4_general_ci |
| Teams                  | utf8mb4_general_ci |
| TermsOfService         | utf8mb4_general_ci |
| ThreadMemberships      | utf8mb4_0900_ai_ci |
| Threads                | utf8mb4_0900_ai_ci |
| Tokens                 | utf8mb4_general_ci |
| UploadSessions         | utf8mb4_0900_ai_ci |
| UserAccessTokens       | utf8mb4_general_ci |
| UserGroups             | utf8mb4_general_ci |
| UserTermsOfService     | utf8mb4_general_ci |
| Users                  | utf8mb4_general_ci |
+------------------------+--------------------+
```

Can you tell me which one of the collations is the correlt one? Is it either `utf8mb4_general_ci` or ` utf8mb4_0900_ai_ci`?
With that information i would be able to apply the changes to the DB and test if it is fixed afterwards ...

Is this maybe a DB migration error? Where did the changes come from?

**Comment by isacikgoz** [comment] 2020-12-07 09:26
Thanks for the great insight @discostur! Probably the reason that I couldn't reproduce this was that I was using postgres. After `MySQL 8.0.1` the [default collation](https://dev.mysql.com/doc/mysqld-version-reference/en/optvar-changes-8-0.html) is set to `utf8mb4_0900_ai_ci` so, I'd suggest to update every table to use default collation depending on your mysql version.

**Comment by discostur** [comment] 2020-12-07 16:21
@isacikgoz thanks for your reply. In the meantime i found this thread in your forums:

https://forum.mattermost.org/t/solved-after-upgrading-to-5-29-messages-fail-to-mark-as-read/10816

I altered all the wrong tables from `utf8mb4_general_ci` to `utf8mb4_0900_ai_ci` which is the default in mysql 8:

```
alter table ChannelMembers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
alter table Channels CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
...
```

Everything is working fine now for me ;)

**Comment by isacikgoz** [comment] 2020-12-07 20:04
Thanks a lot @discostur! We should update the [developer documentation](https://docs.mattermost.com/install/requirements.html#database-software) regarding to this issue. @agusl88 can you also confirm that this fix solves your problems as well?

**Comment by thystra** [comment] 2020-12-08 02:17
Updating the database solved my issue as well.  Thanks @discostur !

**Comment by agusl88** [comment] 2020-12-09 15:25
Hi @isacikgoz 

I changed the collation of all tables to utf8mb4_0900_ai_ci as suggested (my database was in the same state as @discostur, database collation set to utf8mb4_0900_ai_ci  and tables set to utf8mb4_general_ci) , but the notifications i had stuck are still there. Maybe i need to manually delete/update them in the database? They are several months old, my guess is that there is not way to trigger the unread update from the clients.

**Comment by amyblais** [comment] 2021-01-29 16:11
Closing as the documentation has been updated via https://github.com/mattermost/docs/pull/4186,

**Comment by agusl88** [comment] 2021-02-03 13:07
Hi @amyblais  The reported issue is still present, the problem reported by @thystra that got fixed with the changes to the database collations was a different issue. Even with suggested changes to the database, im still getting stuck notifications when working with multiple teams on the same server

**Comment by amyblais** [comment] 2021-02-03 14:47
@agusl88 What Mattermost server version are you on currently?

**Comment by agusl88** [comment] 2021-02-03 19:03
v5.25.5

**Comment by paddy-hack** [comment] 2021-02-24 01:08
Thanks for the info :bow:  
I've now changes all my tables to use `utf8mb4_general_ci`.  There were fewer tables, only six, IIRC, to change that way.

Reading up on the various collations, I thought I'd alter all my tables to the MySQL 8 default, `utf8mb4_0900_ai_ci`, but doing so on a test system did not complete in a reasonable time, say less than 4 hours.  Any idea why this takes such a long time and/or how I can achieve the change in reasonable time?

BTW, my Posts table has close to 400,000 messages, mostly in Japanese.  Changing all other tables completes in  a few minutes but the Posts table takes "forever".  I've let it run for 20 hours

**Comment by amyblais** [comment] 2021-02-24 13:52
@isacikgoz Would Server team have thoughts on ``agusl88``'s or ``paddy-hack``'s issues above? ^

**Comment by isacikgoz** [comment] 2021-02-25 13:55
Sorry @agusl88 this issue escaped from me. Do you still observe the error similar to log line below?
```json
{"level":"error","ts":1607113861.4809077,"caller":"mlog/log.go:229","msg":"Unable to update the last viewed at time.","path":"/api/v4/channels/members/me/view","request_id":"qgfyuk6k778ytd3xknz3ehde1y","ip_addr":"192.168.xxx","user_id":"1aukw8gw3fbzinbz88erkio7ey","method":"POST","err_where":"MarkChannelsAsViewed","http_code":500,"err_details":"failed to fetch threads: Error 1267: Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='"}
```
To be clear, notifications are not stored in the server DB, they are delivered to client and it is managed at the client side whether if they should be cleared or stacked etc.

@paddy-hack I am guessing that the time to update a table may be related to its size since every character will be updated. I don't have the data to evaluate if your experience is normal or not. But you I think you can compare it with your test setup. What was the size of your post table in the test setup?

**Comment by paddy-hack** [comment] 2021-02-26 11:05
@isacikgoz As I mentioned, my Posts tables has close to 400,000 messages.  It uses `utf8mb4_general_ci` for collation now and I am trying to change that to `utf8mb4_0900_ai_ci`.  Seeing that both use the *same* encoding, `utf8mb4`, I don't understand why every character would have to be changed.

From memory, the `mysqldump` of my instance is around 220MB and most of that would be accounted for by the Posts table.

**Comment by agusl88** [comment] 2021-03-08 19:08
> Sorry @agusl88 this issue escaped from me. Do you still observe the error similar to log line below?
> 
> ```json
> {"level":"error","ts":1607113861.4809077,"caller":"mlog/log.go:229","msg":"Unable to update the last viewed at time.","path":"/api/v4/channels/members/me/view","request_id":"qgfyuk6k778ytd3xknz3ehde1y","ip_addr":"192.168.xxx","user_id":"1aukw8gw3fbzinbz88erkio7ey","method":"POST","err_where":"MarkChannelsAsViewed","http_code":500,"err_details":"failed to fetch threads: Error 1267: Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='"}
> ```
> 
> To be clear, notifications are not stored in the server DB, they are delivered to client and it is managed at the client side whether if they should be cleared or stacked etc.

Yes, i can confirm that im not getting any collations errors and that my database and tables are fully converted to `utf8mb4_0900_ai_ci`. The stuck notifications are present in all clients, and they remain stuck even if i reinstall the client (i even manually cleared all the client app cache and local files), so it seems like they are stuck in the push notication server.

I also updated to the new LTS version (5.31) and the notifications remain stuck. I havent tried yet if i can get more notications stuck in new teams to validate if this is just residual stuff from an older bug or is still present in the new version, but will do as soon as i can spare some time to setup the new teams and such.

I think it would be useful to have some CLI commans to clear push notifcations for individual/all users per team.

**Comment by agusl88** [comment] 2021-05-04 16:59
Just wanted to mention that it keeps happening on 5.31

Created a new team, renamed the town square channel, added some people, and after just a few hours they are reporting stuck notifications. If there is anything else i can do to help debug this let me know,

**Comment by amyblais** [comment] 2021-05-04 17:07
@isacikgoz Please help take a look, or let me know if a new ticket should be created for further investigation.

**Comment by isacikgoz** [comment] 2021-05-05 12:03
@amyblais Before creating a ticket I want to get more info on this hence I have some questions to @agusl88 and an apology for the late reply. @agusl88 can you access to `ChannelMembers` table in your DB and confirm that users (for the users who are experiencing the stuck notification issue) has `0` value for the `MentionCount` column? You will need the channel id, and user id to find the channel membership.

**Comment by agusl88** [comment] 2021-05-13 21:20
Hi @isacikgoz 

I ran the following query for my user, that has 3 stuck notificaitons and got some interesting data

```sql
SELECT c.Name, u.Email, mc.MentionCount FROM mattermost.ChannelMembers as mc 
    JOIN mattermost.Users as u ON mc.UserID = u.Id
    JOIN mattermost.Channels as c ON mc.ChannelId = c.Id
    WHERE Email = 'myemail@email.com' and 
      MentionCount > 0;
```

```
Name	DisplayName	Email	MentionCount
general		myemail@email.com	1
general		myemail@email.com	1
general		myemail@email.com	1
```
general is the name i use to rename the Town Square channel on the aditional teams. So the problem is definitely around the rename of the Town Square default channel.

**Comment by isacikgoz** [comment] 2021-05-24 09:17
This looks interesting, the mention count should be cleared once the user visits the channel. Thanks for sharing this @agusl88 🚀 Created a ticket [here](https://mattermost.atlassian.net/browse/MM-35959) to follow up on this.

**Comment by agnivade** [comment] 2021-08-16 04:56
Hey @agusl88, just checking in with this. Are you still experiencing this issue?

**Comment by agusl88** [comment] 2021-08-23 13:14
I cleaned up the stuck notifications we had on the server with the following query, and i run this query every a few days latter after creating new teams on the server.

```sql
UPDATE ChannelMembers mc 
	JOIN mattermost.Channels as c ON mc.ChannelId = c.Id  
    SET MentionCount = 0 
    WHERE MentionCount = 1 and c.Name LIKE  '%eneral%';
```

As i explained [here](https://github.com/mattermost/mattermost-server/issues/16206#issuecomment-733157360), `general`is the name i use to rename the TownSquare default channel. I havent created new teams lately, but given that i managed to reproduce this error in every mattermost LTS version from the last year and a half, is very likely the bug is still there if it hasn't been directly targeted with a fix.

**Comment by agnivade** [comment] 2021-08-23 15:19
Thank you for the update @agusl88 ! I will take a deeper look at this.

**Comment by agnivade** [comment] 2021-08-24 06:17
@agusl88 - Can you confirm something: the problem here is that you get a notification, then visit the channel, but then the team unread icon never goes below 1, correct? And then whatever you do, since there is no unread for a channel, the team unread always persists. Is that accurate?

I am trying to isolate whether the bug is that somehow we are creating a new unread or somehow we are generating an unread which is not tied to a channel.

**Comment by agusl88** [comment] 2021-09-04 00:22
yes, exactly as you described.

**Comment by agnivade** [comment] 2021-09-13 04:59
Thanks for the confirmation @agusl88. This is really strange because unreads are always tied to a channel, and the team unread badge number comes from a SQL query that counts the unreads for all channels.

I was working on this ticket couple weeks back, but failed to reproduce after trying lots of possible things. I will add this comment to the ticket for the next person to work on it.

**Comment by agarciamontoro** [comment] 2021-09-22 11:55
Hi @agusl88, it's me now trying to investigate this issue!One question: how do you change the name of the Town Square channel? I see that in your queries you're selecting `Name` instead of `DisplayName`. The URL

**Comment by agarciamontoro** [comment] 2021-09-22 16:22
An additional question: what's the last version you were able to reproduce this in?

**Closed** 2023-07-27 17:03 UTC
Labels: Bug Report/Open
