### ISSUE TITLE
Negative number of unread threads

### ISSUE THREAD

**Issue by sungam0** [mattermost/mattermost#25724] opened 2023-12-14 16:51 UTC
#### Summary
Bug report in one concise sentence

#### Steps to reproduce
Have a thread opened in the right column. Ask a co-worker to write a comment to that thread. You should see the comment display on your view as soon as it has been posted, but you should also notice that the "Threads" link in the left column becomes bold, indicating you have unread threads. Click on it, and you will see the text "Catch up on your threads / You have -1 threads with unread messages".

#### Expected behavior
You should never have less than 0 unread threads.

#### Observed behavior (that appears unintentional) 
It says I have -1 unread threads when I click on the highlighted "Threads" menu option. (See attached file.) If I get another co-worker to comment on another thread that I don't have currently opened, this number bumps to - surprise surprise - 0 unread threads! (While it actually should be 1 unread thread...)

![Mattermost_unread_threads](https://github.com/mattermost/mattermost/assets/114743587/4af61414-e197-411b-9522-653fc5a6305a)

#### Possible fixes
Haven't checked the code, but it should be fairly easy for you guys to locate it, and just make a check if unread < 0 then unread = 0.

**Comment by amyblais** [comment] 2023-12-14 17:35
Hi @sungam0,
1. What Mattermost server version are you on?
2. What OS and version are you on?

**Comment by sungam0** [comment] 2023-12-18 11:42
1.  Mattermost Team Edition 6.7.0
  2.  Windows 10, Mattermost client version 5.6.0 commit: aebafea (I think, at least that's what it says under Help).

(Isn't this questions you should've asked for in the bug report template?)

Sincerely,
Magnus Hedberg
________________________________
Från: Amy Blais ***@***.***>
Skickat: den 14 december 2023 18:35
Till: mattermost/mattermost ***@***.***>
Kopia: Magnus Hedberg ***@***.***>; Mention ***@***.***>
Ämne: Re: [mattermost/mattermost] Negative number of unread threads (Issue #25724)

Du får inte e-post ofta från ***@***.*** Se varför det här är viktigt.<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi @sungam0<https://github.com/sungam0>,

  1.  What Mattermost server version are you on?
  2.  What OS and version are you on?

**Comment by amyblais** [comment] 2024-01-02 16:11
Thank you @sungam0, we currently support server version v8.1 and newer version. Would you be open to upgrading to a more recent server version?

**Comment by sungam0** [comment] 2024-01-03 11:19
Have now tried to recreate the bug using Mattermost Enterprise Edition, v 8.1.6 without success, so I'm guessing you have solved it (or it's unique for Team Edition?).

Sincerely,
Magnus
________________________________
Från: Amy Blais ***@***.***>
Skickat: den 2 januari 2024 17:11
Till: mattermost/mattermost ***@***.***>
Kopia: Magnus Hedberg ***@***.***>; Mention ***@***.***>
Ämne: Re: [mattermost/mattermost] Negative number of unread threads (Issue #25724)

Du får inte e-post ofta från ***@***.*** Se varför det här är viktigt.<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Thank you @sungam0<https://github.com/sungam0>, we currently support server version v8.1 and newer versions. Would you be open to upgrading to a more recent server version?

**Comment by amyblais** [comment] 2024-01-03 13:36
I'm guessing that the issue is fixed in the v8.1 version. Is the other issue also fixed https://github.com/mattermost/mattermost/issues/25725?

**Comment by sungam0** [comment] 2024-01-03 14:00
I'm not an admin on the Enterprise installation, so I really can't tell (and no, we can't bump our Team Edition at the moment, everyone with server access is currently still on holiday leave). What I did notice now though is that we've added a 27th user, and now the user list says this:

"1-26 of 27 total"

(26 users in the list)

Next page says:

51 - 26 users of 27 total

No users found


But you think this was also fixed in 8.1, or are you guessing/hoping?


Sincerely,
Magnus

________________________________
Från: Amy Blais ***@***.***>
Skickat: den 3 januari 2024 14:36
Till: mattermost/mattermost ***@***.***>
Kopia: Magnus Hedberg ***@***.***>; Mention ***@***.***>
Ämne: Re: [mattermost/mattermost] Negative number of unread threads (Issue #25724)

Du får inte e-post ofta från ***@***.*** Se varför det här är viktigt.<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


I'm guessing that the issue is fixed in the v8.1 version. Is the other issue also fixed #25725<https://github.com/mattermost/mattermost/issues/25725>?

**Comment by amyblais** [comment] 2024-01-03 14:24
I haven't seen other reports on this issue and I'm not able to reproduce it myself on the latest server version, so I cannot say for sure if there was a bug in an older server version that has since been fixed. We can leave this issue open until your team has had a chance to upgrade to a supported server version, and then you can re-test this.

**Comment by amyblais** [comment] 2024-05-01 16:49
Closing for now - we can re-open this if it reproduces on a supported version.

**Closed by amyblais** 2024-05-01 16:49 UTC
Labels: Awaiting Submitter Action
