### ISSUE TITLE
Emojis are displayed when they shouldn't

### ISSUE THREAD

**Issue by TehPeGaSuS** [mattermost/mattermost#24005] opened 2023-07-12 20:24 UTC
[This](https://github.com/mattermost/mattermost/issues/1982) issue was closed, asking to open a `feature idea` which was opened [here](https://mattermost.uservoice.com/forums/306457-general/suggestions/12419022-way-to-turn-off-emoticons).

This `feature idea` was opened more than **7 years** ago and has received ***146*** votes so far.

But, unfortunately, nothing has been done to solve this issue.

The emoji replacement breaks code examples when not inside backticks, etc, being in overall extremely annoying.

Has someone stated, [this](https://imgur.com/gallery/EYn5ZUs) is just silly.

Please consider changing the emoji replacement behaviour, since we have a button **exactly for that** on the input field.

Best regards!

**Comment by amyblais** [comment] 2023-07-13 14:47
Hi @PeGaSuS-Coder , thank you for the feedback! I asked our team about this and here is a summary:

1. From a technical point of view, we are not able to make distinctions between written emojis and emojis added via the emoji picker.

2. To introduce non-formatted text, you can use the backticks. You are already aware of this, but we just wanted to reiterate this point.

3. We are open to a help wanted contribution to disable the emoji rendering on messages on the client side (i.e. control how the user see the messages, not so much how everyone else will see the user messages). Would you be interested in opening a pull request?

**Comment by PeGaSuS-Coder** [comment] 2023-07-13 15:07
Hello @amyblais and thank you for the reply.
> 1. From a technical point of view, we are not able to make distinctions between written emojis and emojis added via the emoji picker.

Well, you absolutely can if the emoji picker follow the emoji standards, since 😀 is `:grinning:` and not `:D`. Se, you have a way on how to make a distinction between them.

> 2. To introduce non-formatted text, you can use the backticks. You are already aware of this, but we just wanted to reiterate this point.

Yes, I'm aware of that but not every user is as technical as I am.

> 3. We are open to a help wanted contribution to disable the emoji rendering on messages on the client side (i.e. control how the user see the messages, not so much how everyone else will see the user messages). Would you be interested in opening a pull request?

Unfortunately I don't know anything about programming, otherwise I'd be glad to help.


_Cheers_

**Comment by amyblais** [comment] 2023-07-14 01:46
I've opened a ticket https://mattermost.atlassian.net/browse/MM-53650 for our team to take a look at opening this as a help wanted issue.

**Comment by PeGaSuS-Coder** [comment] 2023-07-14 08:13
I see that the issue is about `Disable the emoji rendering on messages on the client side` when I'd like to see it globally and being able to be set/unset by admins and then users could "turn it on"

_Cheers_

**Comment by amyblais** [comment] 2024-03-18 14:25
Closing as a Help Wanted issue was opened for this,

**Closed by amyblais** 2024-03-18 14:25 UTC
Labels: kind/feature
