### ISSUE TITLE
High contrast settings on Windows lead to poor color choices in app

### ISSUE THREAD

**Issue by choav** [mattermost/mattermost#18348] opened 2021-08-05 13:23 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
With a high contrast theme in Windows enabled, the user-set color theme in Mattermost desktop gets overwritten with poorly visible colors.

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.7.1
- Mattermost Server version:  5.36.1

**Steps to reproduce**

Choose a high contrast theme in Windows.

**Expected behavior**

Colors in Mattermost should be chosen sensibly.

**Observed behavior**

Mattermost defaults to a high contrast theme. I realize this is intentional, but the resulting colors are chosen poorly. For instance, the font of the active channel and channels with new messages is exactly the same as for other channels, so there is no way to check for new messages in the channel list.

This behavior seems to be caused by Electron, since I observe the same behavior in Chrome. **However**, in Chrome I can turn off this behavior under chrome://flags by setting "Forced Clors" to "disabled". Such an option is missing from Mattermost desktop, afaik.

**Possible fixes**

Add an option to ignore Windows high contrast settings. Another solution would be to choose more sensible colors for high contrast mode, but I assume these colors are set in Electron, so simply ignoring high contrast might be easier to realize.

**Comment by Alwaysin** [comment] 2022-09-16 08:04
I second this issue although I think it is not as bad as it was.
The main problem I'm facing is with the "minimize/maximize/close" buttons that are not visible anymore in high contrast mode, and the first letter of menu words either.

<img width="960" alt="Mattermost_2022-09-16_10-03-51" src="https://user-images.githubusercontent.com/7189936/190588684-f6502a61-7e39-40f5-ba03-f81d679e5785.png">

<img width="209" alt="Mattermost_2022-09-16_10-04-30" src="https://user-images.githubusercontent.com/7189936/190588752-e935f8bf-2745-4932-ae1f-2c10fc9159c3.png">

**Comment by Alwaysin** [comment] 2022-09-16 08:24
ALso, the smiley don't display

**Comment by amyblais** [comment] 2023-12-07 19:27
Closing as we haven't been able to prioritize fixing this. Please let us know if this reproduces on the latest Mattermost version,

**Closed by amyblais** 2023-12-07 19:27 UTC
Labels: Bug Report/Open

**Comment by nimzodisaster** [comment] 2023-12-07 21:21
hilarious that i just looked this issue up just this moment because I was dissatisfied. 
not seeing the edges of the window is frustrating: 
![image](https://github.com/mattermost/mattermost/assets/19696085/2c761773-d21b-4993-ab46-4b392ca9afe2)
Desktop Windows 10: Mattermost Version 5.5.0 commit: 4f266a3

**Comment by Alwaysin** [comment] 2023-12-09 14:25
> I second this issue although I think it is not as bad as it was. The main problem I'm facing is with the "minimize/maximize/close" buttons that are not visible anymore in high contrast mode, and the first letter of menu words either.
> 
> <img alt="Mattermost_2022-09-16_10-03-51" width="960" src="https://user-images.githubusercontent.com/7189936/190588684-f6502a61-7e39-40f5-ba03-f81d679e5785.png">
> 
> <img alt="Mattermost_2022-09-16_10-04-30" width="209" src="https://user-images.githubusercontent.com/7189936/190588752-e935f8bf-2745-4932-ae1f-2c10fc9159c3.png">

On 5.6.0rc1, it' now OK for the first letter of menu words, but still no "minimize/maximize/close" buttons visible and still no smiley.
