### ISSUE TITLE
Work of group info depends on application (webapp/mobile) state

### ISSUE THREAD

**Issue by TiPo4u4eK** [mattermost/mattermost#22436] opened 2023-03-06 09:13 UTC
Summary
Work of group info depends on application (webapp/mobile) state.
May be related to https://github.com/mattermost/mattermost-server/issues/22435

#### Steps to reproduce
1. Create more then 60 groups (default pagination: page=0&per_page=60)
2. Create message with ``@group[60+]``
3. Log in with empty state (private browser window, etc.)

#### Expected behavior
4. Click on group[60+] mention and open group info

#### Observed behavior (that appears unintentional)
4. Group mention of group[60+] is not clickable 

#### State influence
5. Try to find group[60+] in message editor
6. Group mention of group[60+] is now clickable and opens group info

#### Possible fixes
If in post history found new mentions not existing in state - search for them and add to state

**Comment by amyblais** [comment] 2023-03-07 14:57
Opened https://mattermost.atlassian.net/browse/MM-51210.

**Comment by amyblais** [comment] 2023-07-27 18:45
Closing as duplicate of the other issue,

**Closed by amyblais** 2023-07-27 18:45 UTC
Labels: Bug Report/Open
