### ISSUE TITLE
Loading messages while scrolling causes skipping multiple lines

### ISSUE THREAD

**Issue by JToholic** [mattermost/mattermost#18985] opened 2021-11-11 14:32 UTC
#### Summary
When scrolling up through messages, the view will jump up when more messages are loaded, causing it to skip many lines. 

#### Steps to reproduce
OS: Windows 10, 20H2
Application: both mattermost windows app 4.7.0 and web build (https://mattermost.web.cern.ch/, opened via windows edge or firefox)
To reproduce: Go to any direct message or channel with plenty of messages, the screen starts at the bottom, showing the latest message. Scroll up slowly to see earlier messages, with either the mouse wheel or by dragging the side bar. 

#### Expected behavior
I expect the scrolling to be smooth, even when mattermost tries to load more messages (which is the case on my iPhone with IOS 15.0.2, mattermost app 1.47.2). 

#### Observed behavior (that appears unintentional) 
When I scroll up slowly, at the instance of more messages being loaded (indicated by the side bar block getting smaller), the view jumps up for many lines, showing messages way earlier than I was seeing before the jump. 

#### Possible fixes
NA

**Comment by amyblais** [comment] 2021-11-11 16:05
Opened: https://mattermost.atlassian.net/browse/MM-40043.

**Comment by francislavoie** [comment] 2022-02-23 23:33
I'd like to +1 this, my coworkers and I run into this issue very frequently.

Notably, if you scroll _fast_, it doesn't bug out, and it properly pauses scrolling until more loads in... but if scrolling _slowly_, it will start jumping up many lines suddenly instead of consistently scrolling.

If I scroll at let's say 5 scroll ticks per second (moderately slow speed), it happens pretty consistently.

**Comment by titansmc** [comment] 2022-04-21 11:15
we are hit by the same bug, is it a bug in the server side or the client?

**Comment by esethna** [comment] 2022-06-09 14:47
Hi @titansmc, this would likely be a bug with the webapp

@JToholic @francislavoie @titansmc, while we continue to look into this, can you all help confirm your Mattermost server version? Our latest version available is v6.7.0 (with v7.0 coming June 16th), and we recommend updating and re-testing to ensure this is still an issue on the latest. Thanks!

**Comment by JToholic** [comment] 2022-06-09 15:19
> Hi @titansmc, this would likely be a bug with the webapp
> 
> @JToholic @francislavoie @titansmc, while we continue to look into this, can you all help confirm your Mattermost server version? Our latest version available is v6.7.0 (with v7.0 coming June 16th), and we recommend updating and re-testing to ensure this is still an issue on the latest. Thanks!

In my case for both webapp and windows app: 
```
Mattermost Version: cern-ci
Database Schema Version: 82
Database: postgres
```
which I'm not sure is what you need... 

As of now (9th June), when more messages are being loaded (indicated by the change in size and location of the side bar), if I'm scrolling up with a mouse or touchpad, the screen will jump up.

**Comment by francislavoie** [comment] 2022-06-09 15:39
Welp, looks like I have egg on my face. I can't seem to make it happen anymore.

My coworker who was still having it happen today was still on Linux desktop v4.6.1 (because we need to install from the `.deb` by hand, and he's less-technical and didn't think to do it because he thought the notification that the server updated also meant the desktop client updated). I got him updated to client version v5.1.0 and scrolling doesn't seem to cause the jumping around anymore, neither on desktop or on the web client, for both of us.

We're currently using server 6.5.0, since we're using the Gitlab Omnibus release. Using 6.7.0 probably isn't possible for us right now because it would significantly complicate things to try to install it separately.

I can confirm this issue existed even in 4.x releases as well, it was an issue as far as I know since we started using Mattermost, which was roughly in Jan-Feb 2020. We just never complained about it until later cause we chalked it up to "oh they'll probably figure it out" etc

Sorry for noise on twitter :sweat: I feel embarrassed for making noise when it seems like it's already been fixed. But at least we can probably close this issue off then!

**Comment by esethna** [comment] 2022-06-09 23:06
@titansmc @francislavoie no worries at all, we appreciate engaged users, so thank you for keeping us on our toes! 

@JToholic are you able to reach a System Administrator of the Cern instance to find out what Mattermost server version is installed, and if not on latest recommend the Admin upgrades? Since other users have mentioned it seems to be non-reproducible with newer server versions, I think upgrading the server would be the best course of action to take here.

**Comment by amyblais** [comment] 2023-11-17 19:09
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.

**Closed by amyblais** 2023-11-17 19:09 UTC
Labels: Bug Report/Open
