### ISSUE TITLE
9.6.0 - About displays "Mattermost Enterprise Edition" also for Team edition

### ISSUE THREAD

**Issue by omueller** [mattermost/mattermost#26521] opened 2024-03-19 22:13 UTC
#### Summary
Just a small cosmetic bug probably : after upgrade from 9.5.2 to 9.6.0 the "about" screen displays "Mattermost Enterprise Edition" even on a Team Edition installation. 

#### Steps to reproduce
Click on "About"

#### Expected behavior
I 9.5.2 it still displayed "Mattermost Team Edition" 

#### Observed behavior (that appears unintentional) 
"Mattermost Enterprise Edition" displayed on an unlicensed installation. 

#### Possible fixes
N/A

**Comment by omueller** [comment] 2024-03-19 22:16
Screenshot: 
<img width="562" alt="screenshot 2024-03-19 à 22 51 38" src="https://github.com/mattermost/mattermost/assets/629924/d298ab30-5f94-429d-9c0d-55b40e9c14a4">

**Comment by amyblais** [comment] 2024-03-19 23:13
Opened https://mattermost.atlassian.net/browse/MM-57353.

**Comment by marianunez** [comment] 2024-03-20 22:27
> after upgrade from 9.5.2 to 9.6.0

@omueller can you share the link from where you installed the v9.6 ? It may have been the enterprise build. 

I couldn't reproduce this using the team edition build: 

<img width="580" alt="Screenshot 2024-03-20 at 6 26 13 PM" src="https://github.com/mattermost/mattermost/assets/936315/763943bb-e8e9-44cd-b179-42f21dad2fcd">

**Comment by amyblais** [comment] 2024-03-21 12:10
@marianunez I had reproduced it by spinning up a cloud server with ``/cloud create [name] --license te``. But maybe this is not the correct way to test it?

**Comment by marianunez** [comment] 2024-03-21 12:15
> @marianunez I had reproduced it by spinning up a cloud server with ``/cloud create [name] --license te``. But maybe this is not the correct way to test it?

Can you check the info of your test server? Check the image info and it's probably using the Enterprise edition. When creating the cloud test server you can specify the image to use instead

**Comment by amyblais** [comment] 2024-03-21 12:22
Ah ok, that's correct. I'll close the Jira ticket for now, and we can wait for feedback from the reporter.

**Comment by omueller** [comment] 2024-03-25 14:10
Hi @amyblais, sorry for the delay, the distribution link used for this installation was: 
https://releases.mattermost.com/9.6.0/mattermost-9.6.0-linux-amd64.tar.gz
(as in the past for 9.5.3, 9.5.1, etc. where "Team Edition" was correctly displayed).

**Comment by amyblais** [comment] 2024-03-25 14:20
Thanks, does https://releases.mattermost.com/9.6.0/mattermost-team-9.6.0-linux-amd64.tar.gz show it as "Team Edition"?

**Comment by omueller** [comment] 2024-03-27 20:01
> Thanks, does https://releases.mattermost.com/9.6.0/mattermost-team-9.6.0-linux-amd64.tar.gz show it as "Team Edition"?

I don't know as I we never used this url (with "-team") for the installation, as we are following the documentation from https://docs.mattermost.com/install/install-tar.html.   Here under "Download Latest Release", you just have one url (wget https://releases.mattermost.com/9.6.1/mattermost-9.6.1-linux-amd64.tar.gz), to see there are two separate versions you need to check the "Older releases" tab. 

Not sure why there are 2 separate tar.gz files ?  I thought everything was the same, and the "Enterprise" features were then simply activated once licence key was entered.  

So until 9.6.0 it was displaying the right Edition under About, and now it's always Enterprise.  I don't have a test server right now so I cannot test how the other version is behaving, but most probably it is correct there :) 

Best regards, Olivier

**Comment by amyblais** [comment] 2024-04-16 19:12
Closing for now as we weren't able to reproduce this. https://releases.mattermost.com/9.6.0/mattermost-team-9.6.0-linux-amd64.tar.gz is for Team Edition and https://releases.mattermost.com/9.6.1/mattermost-9.6.1-linux-amd64.tar.gz is for Enterprise Edition.

**Closed by amyblais** 2024-04-16 19:12 UTC
