### ISSUE TITLE
Group direct message issues

### ISSUE THREAD

**Issue by user7194** [mattermost/mattermost#23651] opened 2023-06-06 16:55 UTC
#### Summary

Once a direct message conversation with more than two users is closed by a user, that user cannot create or reopen a direct message conversation with those same users.

**Version:** Mattermost 7.8.4

#### Steps to reproduce

1.  Create a direct message conversation with at least two other users
2.  Close the direct message conversation by opening its kebab menu (whether in the sidebar on the desktop or web applications, or in the conversation itself on Android/iOS) and clicking Close Conversation
3.  Attempt to create a direct message conversation with the same users as the previous conversation
4.  An error should be produced that says "Channel Not Found - The channel you're requesting is private or does not exist" (desktop/web app), "Unable to save channel" (Android), or "We couldn't open a group message with those users. Please check your connection and try again" (iOS)

#### Expected behavior

I would expect to be able to create or reopen a direct message conversation, regardless of whether I had closed such a conversation previously or not.

#### Observed behavior (that appears unintentional)

When following the steps to reproduce this issue on the desktop or web applications, the following error is produced: [![mattermost-error](https://user-images.githubusercontent.com/135724699/243756959-0beb0265-d6f1-4769-8fc5-91c82935539a.png)](https://user-images.githubusercontent.com/135724699/243756959-0beb0265-d6f1-4769-8fc5-91c82935539a.png)

This issue occurs regardless of client type (desktop, web, iOS, and Android - Mac is untested).

This issue does not occur with direct message conversations involving only two users (1-on-1 conversations). 

When one user closes the conversation and a separate user then sends a message in that conversation, the conversation will reopen itself.

If all users close the conversation, it is no longer accessible and cannot be recreated.

#### Possible fixes

While I'm unfamiliar with the codebase itself, here's a proposed algorithm:

When opening a direct message conversation, check if a conversation with the specified users already exists.
* *If the conversation exists*:
    * *If the conversation has not been closed*:
        * Display a warning that the conversation already exists
    * *If the conversation has been closed*:
        * Reopen the conversation
* *If the conversation doesn't exist*:
    * Create the conversation

**Comment by marianunez** [comment] 2024-03-20 22:44
@user7194 I am unable to reproduce this in the latest version v9.6. Is this still an issue for you?

**Comment by amyblais** [comment] 2024-03-21 12:08
Closing for now - can be re-opened if the issue persists on the latest ESR (v9.5),

**Closed by amyblais** 2024-03-21 12:08 UTC
Labels: Bug Report/Open
