### ISSUE TITLE
Mattermost Web Client users are displayed as online although they are offline

### ISSUE THREAD

**Issue by jameskitt616** [mattermost/mattermost#25369] opened 2023-11-08 10:18 UTC
#### Summary
Some users who use the Mattermost Web Client are always shown as Online after closing the Browser Tab or Window.

#### Steps to reproduce
Current Server Version: 9.1.0 (issue persisted in the past few versions as well)
Only observed with users who use the Mattermost Web Client.

1. Open Browser (Chrome and Firefox used in this case)
2. Login to Mattermost Web Client
3. Close Browser Tab, Window or shutdown PC
4. The status for the User updates correctly (to Offline) in the DB
5. When Logging into a different User account (or already be logged in. No matter if Desktop, Mobile or Web Client) -> the User *sometimes* is shown as Online forever

To Note:
- After using the functionallity "Revoke All Sessions". All Users where shown as Offline. But after them logging back in via the Web Client the issue persisted again

#### Expected behavior
When a User closes the Browser Tab, Window or shuts down their PC, their status should be changed to Offline/Invisible after a timeout.

#### Observed behavior (that appears unintentional) 
-

#### Possible fixes
-

**Comment by amyblais** [comment] 2023-11-08 14:33
Opened https://mattermost.atlassian.net/browse/MM-55343.

**Comment by jameskitt616** [comment] 2023-11-14 11:01
We observed that this also happens for the Linux Snap Mattermost Desktop App.

**Comment by M0CHIL0** [comment] 2023-12-13 14:44
I have the same problem

**Comment by iwittkau** [comment] 2024-01-04 09:40
Same here.

**Comment by vorlif** [comment] 2024-01-09 19:18
Same here.

* Mattermost Version: 9.3.0
* Client: Browser

**Comment by vorlif** [comment] 2024-01-22 20:31
The same with version 9.4.1. I can confirm that the users are correctly marked as offline in the database. After a restart, the correct status is also displayed. We have therefore now switched to restarting the Mattermost server every night. There are no abnormal entries in the log. 

Is there any other information I can provide to identify the source of the problem?

**Comment by vorlif** [comment] 2024-05-17 11:32
We updated from version 9.4 to version 9.8 today, and it looks like the problem has been fixed.

**Comment by jameskitt616** [comment] 2024-05-23 06:14
Few days later after upgrading to the latest version, we encountered the issue again.

Mattermost Client still being displayed online: Browser Client
Mattermost Server Version: 9.8.0

**Comment by flixr** [comment] 2024-05-23 09:20
The changelog still lists this under known issues: https://docs.mattermost.com/deploy/mattermost-changelog.html#known-issues :
> Status may sometimes get stuck as Away or Offline with IP Hash turned off.

But I could not find this setting anywhere in the docs and how to turn it on.

**Comment by jameskitt616** [comment] 2024-05-23 09:22
We got a slightly different problem. For us Users stay online, eventho they are offline.

**Closed** 2024-05-28 16:36 UTC
Labels: Bug Report/Scheduled for Release

**Comment by jameskitt616** [comment] 2024-06-19 07:04
We installed the latest Mattermost Server release (v9.9.0), but we still got this issue.
Most of the time only one person is affected by this and constantly shown online.
