### ISSUE TITLE
read-only on first join via Mobile app

### ISSUE THREAD

**Issue by cod3monk** [mattermost/mattermost#23814] opened 2023-06-21 07:16 UTC
#### Summary

After joining mattermost server for the first time via App users see channels as read-only.

#### Steps to reproduce

Server setup:
* running latest dockerized enterprise version
* new users join via SAML login and groups are setup via LDAP sync.
* there are three default channels via `ExperimentalDefaultChannels` config

On joining the mattermost service for the first time using the Mobile app on Android, (some?) users see the default channels as read-only until they kill and restart the app.

The team and channel is configured that everyone can join. Regardless of group memberships.

#### Expected behavior

Users should be allowed to write into channels from the start, as this leads to extra support effort.

#### Observed behavior (that appears unintentional) 

Nothing else out of the ordinary.

#### Possible fixes

Unsure where to start looking.

**Comment by amyblais** [comment] 2023-06-21 12:45
Hi @cod3monk, does this happen on webapp or desktop app? Do you see any errors in Mattermost server logs?

**Comment by cod3monk** [comment] 2023-06-21 15:21
I believe the error occurred with the webapp or native app on android.

The only error I see in the logs lately is of this type:
```
{"timestamp":"2023-06-19 23:18:30.826 +02:00","level":"error","msg":"websocket.NextReader: closing websocket","caller":"app/web_conn.go:828","user_id":"xxx","error":"read tcp 172.20.0.17:8065->172.20.0.16:54926: i/o timeout"}
```

**Comment by amyblais** [comment] 2023-06-21 16:28
Opened https://mattermost.atlassian.net/browse/MM-53288.

**Comment by cod3monk** [comment] 2023-08-26 10:52
@amyblais 
Thanks for taking the time. I am not aware of anything else that might cause this behaviour, but you can try yourself at https://chat.zam.haus

**Comment by plaxique** [comment] 2023-09-05 10:55
I had the same issue. I was not able to write in Mattermost's channels when i first installed the app and 'logged' into ZAM. 

Android Version: 13
App Version: 2.7.0
Mobile: Pixel 6

**Comment by mgmax** [comment] 2023-11-12 17:29
I had the same issue with ZAM

App 2.9.1 on Android
Server 9.2.2

**Comment by unaimed** [comment] 2023-11-12 18:55
I am also affected:

Mobile Client:
App Version: 2.9.1 (Build 6000491)
Server Version: 9.2.2 (Build 6801073174
Datenbank: postgres
Version des Datenbankschemas: 113

**Comment by cod3monk** [comment] 2023-11-14 10:01
Hi @amyblais,
1. I am the admin of the system referred to
2. We have one read-only channel, but thats not the channel they are referring to. The "townsquare" is not read-only
3. We are not using group or role permissions, because there is no non-profit discount for the enterprise license (which we would love). We are only using SSO and LDAP user-sync.

The permission problem only ocurres on the first use of mattermost mobile app, right after account creation through SSO login. After restarting the app (manually swiping it closed and reopening) everything works as intended. Since we are onboarding many users with self-registration this a problem for their experience.

**Comment by amyblais** [comment] 2023-11-14 13:51
Thanks, I added those details to the Jira ticket.

**Comment by cod3monk** [comment] 2024-01-12 19:39
@amyblais do you have any updates on this issue?

**Comment by amyblais** [comment] 2024-01-12 19:58
Hi there, I don't have new updates on this. Looking at the Jira ticket, it looks like product team hasn't been able to reproduce this and they haven't been able to prioritize this issue. As an option, perhaps you can share about this issue on our troubleshooting forums (https://forum.mattermost.com/ and https://community.mattermost.com/core/channels/peer-to-peer-help) to see if anyone on the community might have thoughts on this issue.

**Comment by cod3monk** [comment] 2024-01-12 23:40
You could try it out on our system: https://chat.zam.haus registration via SSO is open to the public

**Comment by amyblais** [comment] 2024-09-05 20:52
Closing older issues as our team hasn't been able to reproduce this,

**Closed by amyblais** 2024-09-05 20:52 UTC
Labels: Bug Report/Open
