### ISSUE TITLE
System Bot missing after migration to PostgreSQL, unread channels don´t show up bold anymore

### ISSUE THREAD

**Issue by Twilek-de** [mattermost/mattermost#24178] opened 2023-08-03 07:22 UTC
#### Summary
System Bot missing after DB migration, unexpected behaviour of channels with unread posts

#### Steps to reproduce
I use Docker Team Edition. After last announcement that PostgreSQL is the preffered and supported DB I bulk exported the data from my installation. Changed the DB to PostgreSQL and bulk imported them again. Now the System Bot does not show up in Bot Accounts and every 5 Minutes I get a 
{
  "caller": "app/post.go:2164",
  "error": "SqlBotStore.Get: Bot does not exist., resource: Bot id: iyu5tpwcn7dt5e5641nyncm4br",
  "level": "error",
  "msg": "Failed to get system bot",
  "timestamp": "2023-08-03 06:55:00.008 Z"
}
in the logs. The only wrong behaviour I am seeing is that channels with unread messages do not show up in bold in the sidebar anymore. I don´t know wether thats connected

#### Expected behavior
Existing system bot. No errors in log. Channels with unread messages show up as bold.

#### Observed behavior (that appears unintentional) 
No system bot. Errors in log. Channels with unread messages look like ones without.

**Comment by amyblais** [comment] 2023-08-03 13:27
Opened https://mattermost.atlassian.net/browse/MM-53917.

**Comment by agnivade** [comment] 2023-08-08 04:09
@isacikgoz - Would you have the bandwidth to look at this? I am wondering if the bot id is persisted somewhere and since a new bot would get generated during the import, it would result in an id mismatch?

@Twilek-de - Could you please outline the exact steps that you performed to do the export and import?

**Comment by Twilek-de** [comment] 2023-08-08 06:25
My Mattermost Installation used MariaDB. After the last announcement of Mattermost that PostgreSQL was the preferred database and reading that some plugins had already stopped working with MySQL I decided to migrate to Postgres. 
I first bulk exported my data via mmctl in local mode. I then spun up the new database, changed the db string in mattermost and started up mattermost. After it had initialized the new db I bulk imported the data again vie mmctl in local mode.
After that it only had the Mattermost App bot and the errors in the logs started showing up.
Yesterday I tried to generate a new bot with Admin priviliges and changed it´s ID in the database to what Mattermost was expecting in the logs. Then mattermost I think tried to regenerate the Systembot itself and gave it different privileges. My Bot Page now looks like this. The errors in the log have dissappeared. I don´t know wether the bot is working as it should as I have no idea what it is supposed to do.
![Screenshot 2023-08-08 082349](https://github.com/mattermost/mattermost/assets/8283684/84802475-d6f9-4d51-9cf8-43cce65fde55)

**Comment by agnivade** [comment] 2023-08-25 05:47
I think there was some issue in the migration. We are in the process of providing official migration steps for MySQL to Postgres. Note that we don't support MariaDB, so there might be issues migrating from MariaDB to Postgres.

I will close this one for now since the issue is resolved. If anyone runs into problems following the official migration steps, we can create a separate issue.

**Closed by agnivade** 2023-08-25 05:47 UTC
Labels: Bug Report/Open
