### ISSUE TITLE
Date picker for custom status hangs on time shift day

### ISSUE THREAD

**Issue by ulab** [mattermost/mattermost#25194] opened 2023-10-27 18:12 UTC
#### Summary
When setting my own away status to 2023-10-29, mattermost becomes unresponsive.

#### Steps to reproduce
Use the custom status selector and select 2023-10-29. Once you do so the interface stops responding in the app. 

Doing so in a browser tab makes Firefox report that "a script is slowing down the browser".

I am wondering if it is a timezones issue. In Germany we switch from summer to winter time on the 29th. So you might not be able to reproduce it if you are in a different timezone.

Earlier and later dates work just fine.

#### Expected behavior
I should be able to select 2023-10-29.

#### Observed behavior (that appears unintentional) 
The App stops working and has to be restarted.

**Comment by amyblais** [comment] 2023-10-27 18:46
Hi @ulab,
1. What Mattermost server version are you on?
2. What Firefox version are you on?
3. Do you see this on webapp or the desktop app?
4. Do you see errors in the Developer Tools > Console?

**Comment by ulab** [comment] 2023-10-27 19:26
1. I am using Mattermost-Version: 9.0.0 bundled with gitlab-ce 16.5.0-ce.0 omnibus, 

2. Firefox: 118.0.2 and MM App: Version 5.5.0 (5.5.0)
3. Both
4. No. Neither in the Firefox Console, nor in the "Developer Tools for Application Wrapper" or "Developer Tools for Current Server"

The browser reports 

<img width="613" alt="Screenshot 2023-10-27 at 21 16 36" src="https://github.com/mattermost/mattermost/assets/504616/8454dc1a-5c7a-41df-b986-42a578e67386">


Debugging the script and stepping through it for a few steps looks like it might be stuck in  the `while (time.isBefore(nextDay)) {` loop in `const getTimeInIntervals = (startTime: Moment): Date[] => {`, but I can only step through so many steps… :-)

**Comment by amyblais** [comment] 2023-10-27 20:52
Thank you, opened https://mattermost.atlassian.net/browse/MM-55192.

**Comment by ulab** [comment] 2023-10-28 09:59
A coworker just tested a little more. 

1. Selecting the last Sunday of March 2024 works (which is the change from winter to summer time = +1 hr)
2. Selecting the last Sunday of October 2024 breaks (summer -> winter = -1 hr)

Which makes us believe it's the "turning back of time" that is the issue.

**Comment by amyblais** [comment] 2023-10-31 13:18
@ulab Our QA team tested this and were unable to reproduce this issue in the latest version of the desktop app v5.5.1, Windows 10. Also couldn't reproduce in Firefox 119.0, Windows 10. They are in the GMT+4 timezone and they do not have any daylight saving changes in this timezone.

Is there any additional information that could help us reproduce this issue?

**Comment by ulab** [comment] 2023-10-31 21:30
Well, I am very sure it's a daylight savings issue, so you'd need someone in a timezone that does this :).

In Germany, the next switch from Summer to Standard time is 2024-10-27.

I have created a screenshare to show what's happening if that helps:

https://youtu.be/D0RSotN_X08

The video will get deleted once this issue gets closed.

**Comment by amyblais** [comment] 2023-11-07 17:26
Closing as a Help Wanted issue was opened for this.

**Closed by amyblais** 2023-11-07 17:26 UTC
Labels: Bug Report/Open
