### ISSUE TITLE
Unable to list user preferences with mm_ctl --local

### ISSUE THREAD

**Issue by grosjo** [mattermost/mattermost#27857] opened 2024-08-05 21:32 UTC
#### Summary
mm_ctl does not retreive user preferences

#### Steps to reproduce
type "mmctl --local user preference list  myuser@domain"

#### Operating System
Archlinux

#### Mattermost Server Version
9.11

#### Expected behavior
Return the user preferences

#### Observed behavior
Error

#### Log Output
Error: 1 error occurred:
	* unable to list user preferences myuser@domain: Sorry, we could not find the page., There doesn't appear to be an api call for the url='/api/v4/users/cp17yakxat818rr4tdzz7db7sh/preferences'.  Typo? are you missing a team_id or user_id as part of the url?

**Comment by amyblais** [comment] 2024-08-06 16:56
Opened https://mattermost.atlassian.net/browse/MM-60024

**Comment by agnivade** [comment] 2024-08-12 06:33
Duplicate of https://github.com/mattermost/mattermost/issues/26864. PR already exists for this.

**Closed by agnivade** 2024-08-12 06:33 UTC
Labels: Bug Report/Open
