### ISSUE TITLE
Direct message channel limit is tooo low (limit_visible_dms_gms)

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost#29372] opened 2024-11-22 22:17 UTC
#### Summary
It seems that one can decide to see between 10 to 40 direct message channels.

-> https://docs.mattermost.com/preferences/customize-your-channel-sidebar.html#manage-direct-messages

We have more than 100 users on our 5000+ User instance with more than 40 DM channels and 10 People with more than 100.

We would need bigger steps than 10-40, like 50, 75, 100, 150, 200, 250, 500 or make the steps configurable by system admins.

The tradeoff between performance and completeness should be a user decision.

#### Steps to reproduce
-> https://docs.mattermost.com/preferences/customize-your-channel-sidebar.html#manage-direct-messages

#### Operating System
Irrelevant

#### Mattermost Server Version
Mattermost Version: 10.2.0
Database Schema Version: 127
Build Number: 11561493190

#### Expected behavior
Let me select a higher number.

Let the server admin change the maximum, or the steps.

#### Observed behavior
One can choose only between 10 to 40.

Much more would be needed.

**Comment by amyblais** [comment] 2024-11-25 09:21
Closing as a duplicate of https://github.com/mattermost/mattermost/issues/29223.

**Closed by amyblais** 2024-11-25 09:21 UTC
