### ISSUE TITLE
Can't close Link Preview in Global Threads View when using Markdown Image Format

### ISSUE THREAD

**Issue by NorthernSeaCharting** [mattermost/mattermost#26252] opened 2024-02-17 11:49 UTC
#### Summary
Cannot close link preview (for images especially) when viewing messages in a thread in the **global threads view** (as opposed to clicking on the thread in the channel directly) when using Markdown Image Format.

#### Steps to reproduce
Hello, I am using the newest desktop client `Version 5.6.0 commit: aebafea` both on linux and windows and the `mattermost/mattermost-enterprise-edition:release-9.4` docker image on version 9.4.2.
\* Edit: Updated the server to 9.5.1, issue persists

1. Write a message in any channel
2. As a reply to the message, post a gif via gif picker or an image link with markdown formatting
  (example: `![Show](https://tse3.mm.bing.net/th?id=OIP.iSu2RcCcdm78xbxNDJMJSgHaEo&pid=Api)`) 
3. Open the thread in global threads view
4. Hover over the image

#### Expected behavior
I would expect that I could close the link preview of a gif or image with markdown formatting in this view just like I can when opening the thread directly.
I think that this was still possible a few versions ago but then all of a sudden, this issue appeared.

#### Observed behavior (that appears unintentional) 

Only one of the views allows me to close the preview. This is consistent across channels and threads. The global view is missing the option to close the link preview.

Example Images (removed personal details not relevant to the ticket):

**Opening the thread in global thread view:**
![thread missing close link preview](https://github.com/mattermost/mattermost/assets/57102171/04aa6e2a-f7f6-4b86-85b8-5c6a31cd4cf4)

Here, the close preview button is missing on the upper image (that is not the direct link preview but done with markdown).

<br/>
<br/>

**Opening thread directly in channel on the post:**
![thread in channel with close preview](https://github.com/mattermost/mattermost/assets/57102171/c1f27f3c-68e5-47e3-adc8-79b9c29c3cb7)
Here, the button is visible and clickable in the top left.

#### Note

By the way, when the link preview is already closed, it can be opened in both views. However, once it is opened, it cannot be closed again in the global view.

Again, I have scanned the issues page to see if there is a similar issue reported but couldn't find one. If there is, I would glady accept this issue being closed.

Thanks in advance for your time and effort.

**Comment by amyblais** [comment] 2024-02-20 18:28
Opened https://mattermost.atlassian.net/browse/MM-56930.

**Comment by amyblais** [comment] 2024-09-05 20:28
Closing older issues as I'm currently not able to reproduce this,

**Closed by amyblais** 2024-09-05 20:28 UTC
Labels: Bug Report/Open
