### ISSUE TITLE
Threads view never finishes loading - only on desktop app (mobile app works with same user)

### ISSUE THREAD

**Issue by KlavsKlavsen** [mattermost/mattermost#23690] opened 2023-06-09 06:01 UTC
#### Summary
Threads view never finishes loading - only on desktop app (mobile app works with same user)

#### Steps to reproduce
desktop app 5.2.2 and then updated to 5.3.1 - issue is same.
server side is running: mattermost/mattermost-team-edition:7.9.0@sha256:edbbc9e28763e1dd94e6580e63cf5c9cc544022d4c5e2eb44b7eea6bcc044394 (on k8s)

#### Expected behavior
threads should show.

#### Observed behavior (that appears unintentional) 
for a long while - I could experience the same - then i switched away from threads view and back again and it would show immediately. for the last few days - it won't ever show - no matter how long I let it stay on "loading".
I see threads on my mobile app right now :(
I have tried clearing cache etc - and other colleagues - using same desktop app version does not have the problem.

**Comment by KlavsKlavsen** [comment] 2023-06-09 08:54
threads view works in a diff. team - which has a lot fewer messages/threads where I am in. But even then - same threads view - works for mobile.. so desktop must be doing something else - to make it never finish loading.

**Comment by KlavsKlavsen** [comment] 2023-06-09 10:47
I think the issue is the PG backend is not fast enough - so in that team I have "too many threads" - and it falls on the "timeout" - but client side does not show that - and offers no way to fix it.
I think maybe threads should be "limited" - so tables for threads is split into "monthly" tables - so smaller tables can be used (aka. DB partitioning) - as I don't care about last months threads really - so that would perform better - even if I have many threads..

**Comment by KlavsKlavsen** [comment] 2023-06-13 07:28
@amyblais we're running in k8s- cluster has servers of this spec:  Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz, with 32gb mem. IO is on ceph (using 1gb links - so most likely its simply because pg isn't 'as fast' and I participate in too many threads).
Logs:
[podlogs.txt](https://github.com/mattermost/mattermost/files/11731849/podlogs.txt)

**Comment by KlavsKlavsen** [comment] 2023-06-13 07:31
it is IO performance thats too low - so reponse is too slow - when I click threads view - on the node the pod is running on I see IO-wait of 25 until it gives up.
I still believe splitting up threads so it does not have to go through such a big heap to find my threads would help lower IO needs.. and oddly enough "there is a way" - to make it work - as it works on mobile - which I suspect simply asks for a smaller subset of threads?

**Comment by hmhealey** [comment] 2023-06-14 20:25
@amyblais Yeah, please do

@KlavsKlavsen If you could open the dev tools (View > Open Developer Tools For Current Server), go to the network tab, and try to view the Threads page in the app, do any of the requests hang or take a long time to complete? The one I'd wonder about in particular is `/api/v4/users/<user id>/teams/<team id>/threads?threadsOnly=true` specifically since I think that's the one used to populate the thread list. That should help us figure out if the issue is on the server or network side.

If nothing stands out there as taking more than a few seconds at the absolute most, could you see if there are any errors in the console there? Since you don't have that issue on mobile and you said other users don't have it either, it's possible that the issue is because you're following a certain thread that just causes that part of the web app to error out while it's loading

**Comment by KlavsKlavsen** [comment] 2023-06-15 08:01
@hmhealey I did what you asked - and thread view ended with showing "no unread threads" - even though it was "white" - and on mobile it shows many threads that has unread updates.
here's the network tab while waiting for it to respond with that:
![image](https://github.com/mattermost/mattermost/assets/2737885/39690e8a-c1d7-48ea-97c6-f84fcb93abaf)

**Comment by hmhealey** [comment] 2023-06-15 19:29
Huh, so it is timing out. I actually didn't expect for that to be the case since we've had quite a few bugs in the past where some network request will complete, but it'll look like it froze to the user because it simply never updated to show that there was a result. I know there were some performance issues with the Threads view in the past, so I'll see if those might have been resolved since 7.9.0

**Comment by hmhealey** [comment] 2023-06-15 19:30
Oh, the server logs you'd posted also included that as well. I didn't think to check those before since I didn't expect they'd show that error for some reason. Sorry about that 😅

**Comment by KlavsKlavsen** [comment] 2023-06-27 09:26
Really annoying that I have to view threads on my mobile client - to see the threads.. and then scroll up - and see where the thread can be found manually - so I can find it on desktop :(
Soo hoping for atleast an "option" in desktop-client - to use "mobile lightweight threads" api.. since such one clearly exists and works for mobile client .) (and seems to lower backend server load)

**Comment by hmhealey** [comment] 2023-06-29 14:32
Sorry for the radio silence recently. We've been busy lately and haven't been able to get to this yet.

Your message made me wonder why mobile behaves differently. It's possible that it has more caching going on so you don't notice that the request is slow, but hopefully that's not the case.

I did notice that mobile's version of that API request doesn't have the `extended=true` option that's used there, so I assume that's the culprit. As best I can tell, that option changes whether or not it returns the users that participated in each thread. I don't know why that would cause the call to take that much longer since the query seems like it would be straightforward enough, but that's my best guess for a cause at the moment.

Perhaps we could see if changing that option changes anything? Could you try:

1. Going back to that view with the network tab open in the dev tools
2. Wait for the request to fail
3. Copy the request URL
4. Change `extended=true` to `extended=false` in it
5. Go to the JS console and run `fetch('<the modified url>')`
6. Watch the network tab for the new request

If it completes much quicker, we'll know for sure that that's the culprit.

And if that is the case and you're following any threads with a particularly large number of users participating, you could try unfollowing those from mobile to see if that helps the performance on the web.

**Comment by KlavsKlavsen** [comment] 2023-06-30 06:30
I tried, and it failed the same way - after 30 seconds - getting a 500.

**Comment by KlavsKlavsen** [comment] 2023-06-30 06:30
![image](https://github.com/mattermost/mattermost/assets/2737885/80b947d0-3d67-4e5d-97c3-f512e5898993)

**Comment by KlavsKlavsen** [comment] 2023-06-30 06:50
I tried going through list of followed threads on mobile and unfollowed a lot of 50+ reply threads.. (patience allowing.. got only around 20 - most threads are 2-30 - so its a HUGE list :)
It did not help.
I always changed postgresql timeout (from 30 to 50 seconds) - to see if that helped - but the request still stops after 30 seconds.. don't know if I have to restart mattermost client for this to take effect?

**Comment by KlavsKlavsen** [comment] 2023-06-30 06:51
Also - I found no way to "have it automaticly clean up old messages" ? 
to avoid this growing for ever - I would not mind being able to set a "6 months" forget limit or something :)

**Comment by KlavsKlavsen** [comment] 2023-06-30 06:52
(also in relation to GDPR - I'd have to be able to actually delete old messages of previous employees - as I'm thinking that may be a violation of GDPR to keep them - hence the auto-cleanup feature would come in handy - and we really should not rely on having to dig out that old info from mattermost.. even though it has been useful sometimes :)

**Comment by hmhealey** [comment] 2023-06-30 15:18
> I tried, and it failed the same way - after 30 seconds - getting a 500.

Damn, I was hoping that might be an explanation for the difference. Looking back at the logs, I think I've tracked down the error to [this line](https://github.com/mattermost/mattermost/blob/master/server/channels/store/sqlstore/thread_store.go#L344) which occurs before we would've checked the value of `extended` anyway. The error I'm seeing repeatedly for the same user ID (which I assume is you) is a 500 error with:
```
GetThreadsForUser: Unable to get user threads, failed to get threads for user id=USERID: failed to fetch threads for user id=USERID: pq: canceling statement due to user request
```

I guess it's possible that the only reason mobile doesn't suffer from the same issue is that it's only fetching threads that have changed recently, not the older ones. Unlike the web app, it stores data when you close it, so it doesn't have to use the heavier API here.

> I tried going through list of followed threads on mobile and unfollowed a lot of 50+ reply threads.. (patience allowing.. got only around 20 - most threads are 2-30 - so its a HUGE list :)
It did not help.

I don't know if that would have as much of an effect, but it's definitely possible. I know I've been in longer threads before (the longest I remember was at least 200 posts), but that was usually surrounded by 2-5 post ones.

> I always changed postgresql timeout (from 30 to 50 seconds) - to see if that helped - but the request still stops after 30 seconds.. don't know if I have to restart mattermost client for this to take effect?

It looks like MM has its own timeout defined as `SqlSettings.QueryTimeout` which you're hitting. That seems to fit with the above error message since "canceling statement due to user request" seems to indicate that MM triggered the timeout, not Postgres

> Also - I found no way to "have it automaticly clean up old messages" ?
to avoid this growing for ever - I would not mind being able to set a "6 months" forget limit or something :)

That does exist, but it's only available with one of the levels of paid license. It's under the name Data Retention, but it's probably not visible in Team Edition which you're using

**Comment by hmhealey** [comment] 2023-06-30 15:25
Anyway, I've asked around a bit to see if anyone more familiar with this code has more ideas since I tend to work closer to the frontend.

Once suggestion I did get was that you could try to run `VACUUM ANALYZE posts, threadmemberships` on the database to try to clean up those tables a bit. It was pointed out to me that this is such a heavy query because it relies joining the Posts, ThreadMemberships, and Threads tables together, and I do know that the Posts table is usually massive.

**Comment by KlavsKlavsen** [comment] 2023-07-04 13:20
@hmhealey Thank you. I tried to run that. It took ~10 minutes to run - and finished fine - but it didn't change anything :(
Threads still work on mobile (thank god) - so I jump back and forth - and have to go "find the thread - from looking in mobile - to avoid responding via mobile keyboard as needed :)

**Comment by KlavsKlavsen** [comment] 2023-07-04 13:21
I use the desktop app - it would really be nice if it could store data too then :)

**Comment by KlavsKlavsen** [comment] 2023-07-04 13:29
or if query could be adjusted to only query for "last X period" - like 30 days or something in "normal query". that would help with this "not so big DB".

As I expect you now - I would recommend a Table partitioning scheme for larger scale - to avoid taking such a toll on a single DB. Partitioning makes query scaleable. (and lowers cost for partial queries - when you query on same as tables are partitioned on).

Partitioning is also what would enable a query client to f.ex. automaticly run "subqueries in partition queries" on seperate instances (ie. do scaling on read-only instances) etc. - and it allows for a high performance by needint to load only data "for the partition period" when querying 'recent' data - or whatever you partition on.

Currently the DB design seems built for vertical scaling - which means bigger and bigger db/IO/mem - much more expensive and has a ceiling - that horizontal scaling pushes much futher away.

**Comment by KlavsKlavsen** [comment] 2023-07-05 07:08
I just realized a trick - for anyone else having this issue. In mobile client I can simply click "save" on the response I want to find in desktop client - and then I can go find it under saved - and respond on the computer.. its faster than finding the thread manually :)

**Comment by KlavsKlavsen** [comment] 2023-07-31 07:37
@hmhealey after having to re-login on my mobile client (rarely happens) - it now can't see all threads anymore.. I used to be able to see threads on mobile, then click threads on desktop - and click away after a while - did not even need to wait for timeout, and then it updated to show no outstanding threads in desktop view..
But now desktop things I have 3 mentions in threads and mobile only showed one thread :(

**Comment by KlavsKlavsen** [comment] 2023-07-31 08:02
is there an sql or a set off sql's I can run to remove old threads to atleast "fix this".. I'd be fine with just deleting

**Comment by KlavsKlavsen** [comment] 2023-08-01 05:53
We just upgraded to 8.0.1 and the problem persists :(

**Comment by KlavsKlavsen** [comment] 2023-08-01 08:49
perhaps that my mobile app had an empty cache.. so maybe some requests from that - slowly "built up" - what desktop needed?

**Comment by KlavsKlavsen** [comment] 2023-08-01 08:50
it seems - if my colleague uses thread view on mobile.. then his desktop view works again.. So its definetely something there.

**Comment by KlavsKlavsen** [comment] 2023-08-07 06:32
It seems its "starting to come back".. almost always (if not always) - first time I click to threads.. it hangs forever.. but I can fix it, by switching to diff. channel and then back to threads. Thats how it started previously, so I'm fearing its building up again

**Comment by hmhealey** [comment] 2023-08-15 17:40
If I had to guess, perhaps the request sometimes completes based on the server load, and mobile is able to handle that case a bit more gracefully since it stores the thread state between sessions.

Going back to the server-side issue though, I'm not much of a database guy, but if I had to guess, it seems like Ceph's performance when running a database may be what's causing these issues. I've never used it myself, but doing some quick googling, there's quite a few people recommending not running Postgres or other databases directly on it for performance reasons. There are some comments about using RBD instead of CephFS and tweaking the block size for it, but I have 0 experience with it so I don't know if that's even relevant here. It does seem like the general recommendation is to run the database on regular storage and only back it up to Ceph though.

**Comment by KlavsKlavsen** [comment] 2023-08-17 06:47
@hmhealey Well.. yeah - you can always "scale up" - on IO as well - and yes even a badly designed DB structure will often perform. That only works "so far" though - and then you're in  bad place and have no way to scale anymore (or you're paying a LOT for hefty IO. So running on Ceph - which IS slower IO than nvme etc. - just highlights something that WILL become a problem for larger mattermost instances - even on higher performance machines.

Our plan is to migrate all postgresql instances to local nvme and do clustering in postgresql to have redundancy/failover - that should help a lot - but that does not remove the badly designs sql here. (I've been working with high performance websites - 8k+ req/sec easily for many years - so I'm maybe a bit focused on 'high traffic paths' and performance - and not needlessly throwing IO/CPU/Memory at a problem (its like pissing your pants - it'll come back to be a problem and it'll be even worse :)

**Comment by amyblais** [comment] 2024-09-06 17:16
Closing for now as we haven't been able to reproduce/prioritize this,

**Closed by amyblais** 2024-09-06 17:16 UTC
Labels: Bug Report/Open

**Comment by klifa90** [comment] 2025-01-23 19:01
This still happens. In our server, it happens to only a few people who have many followed threads. Is there a way to mass unfollow threads?

Client: 5.2.2
Server - Selfhosted: 9.4.1

Been using mattermost for almost 6 years, and threads since beta.

![Image](https://github.com/user-attachments/assets/bea96658-ef28-4a8b-9f53-b3713730286d)

![Image](https://github.com/user-attachments/assets/7a75dc3c-230f-4f51-8c2f-ba9c04fd4472)

**Comment by KlavsKlavsen** [comment] 2025-01-23 21:47
mattermost runs some sort of cleanup - so after upgrading - it cleaned up enough so it ran okay again.
Plan is to migreate postgres to a local nvme storage - so it'll be faster - as that'll fix it.

**Comment by KlavsKlavsen** [comment] 2025-01-24 07:38
@klifa90 There really should be a server-side option to "unfollow threads older than X months automaticly for everyone" - to ensure that threads don't keep causing bigger and bigger SQL resources.. I'd suggest you open a feature request for that.

**Comment by dmitry-vychikov** [comment] 2025-04-14 11:56
> Closing for now as we haven't been able to reproduce/prioritize this,

@amyblais can you consider reopening this please?

It is still reproduced for me using:
- Mattermost server: `10.7.0`
- Mattermost Desktop: `5.11.2 (137884318101)`

It cannot be reproduced on Mobile IOS though (App version `2.2.26 (Build 620)`)

Please let me know what information is needed and I will try to assist in reproducing it. This is a critical problem for me that prevents from using Threads.


Also, others reported that Mobile and Web versions have difference in how the API for threads is called (https://github.com/mattermost/mattermost/issues/23690#issuecomment-1613291914).

Is `extended=true` really not being the problem for Desktop? Can it not be fixed that way to bring Mobile and Desktop into parity?
