### ISSUE TITLE
Wrong return value

### ISSUE THREAD

**Issue by iamleson98** [mattermost/mattermost#23606] opened 2023-06-03 02:52 UTC
Please take a look at this function (link below)
Inside the function's body

Initially we find 1 user by given email
We do check if returning err is nil or not.
But in case it's NOT nill, we have to return that error instead of nil.

If an user enter wrong email, 
He would receive no reset email in the inbox and have no idea what was wrong about his action.

Thank you for reaching out, mr @agnivade, mr @jwilander 

https://github.com/mattermost/mattermost/blob/789f84af9085969fb37c440336384fc25b1939c8/server/channels/app/user.go#L1454

**Comment by amyblais** [comment] 2023-06-05 13:52
Hi @iamleson98,
1. What Mattermost server version did you see this issue on?
2. What are the reproduction steps and expected behaviour in this case?

**Comment by amyblais** [comment] 2023-06-27 16:32
Hi @iamleson98, kind reminder on the above questions.

**Comment by iamleson98** [comment] 2023-06-29 13:36
Hello @amyblais madam!

I just browse the master branch and detect the problem (my own opinion).

If every development of Mattermost results to the master branch being updated with latest code, 
then definitely the latest release is having the problem.

If my reasons was wrong, please kindly let me know!

**Comment by amyblais** [comment] 2023-07-05 16:25
Thanks, opened https://mattermost.atlassian.net/browse/MM-53489.

**Comment by hanzei** [comment] 2023-08-21 09:38
> If an user enter wrong email,
He would receive no reset email in the inbox and have no idea what was wrong about his action.

That might be by design. Otherwise, an attacker could scrape the API to get a list of all e-mail addresses.

@esarafianou Can you confirm that?

**Comment by esarafianou** [comment] 2023-08-22 10:17
I'm not understanding the initial request. Even if we were to send an email to the wrong email, the user would still not receive anything since it's the wrong email (not the user's one).

In any case, from a security standpoint, we don't send such emails also because that would allow an attacker to use an unauthenticated endpoint (reset password) to spam the mailbox of random people.

**Comment by hanzei** [comment] 2023-08-22 10:44
The point of OP is (I think) that the UX is not confusing if the user inputs a wrong email address. The UI shows that an email was sent, but in fact, it wasn't, because the user connected to the email address was not found.

**Comment by esarafianou** [comment] 2023-08-22 11:26
Ah, thanks for clearing out my confusion! This is indeed to not disclose which emails are valid emails and which are not.

**Comment by hanzei** [comment] 2023-08-22 19:40
Thanks for the clarification. I'm going to close this issue as won't fix.

**Closed by hanzei** 2023-08-22 19:40 UTC
Labels: Invalid
