### ISSUE TITLE
Bleve search doesn't find text in attachment posts

### ISSUE THREAD

**Issue by bryantgeorge** [mattermost/mattermost#23697] opened 2023-06-09 18:20 UTC
#### Summary
When Bleve is enabled for search queries, the text of posts that include [attachments](https://developers.mattermost.com/integrate/reference/message-attachments/) doesn't seem to be indexed

#### Steps to reproduce
1. Create a message with text and an [attachment](https://developers.mattermost.com/integrate/reference/message-attachments/)
2. Search for the message's text, and the post doesn't appear

#### Expected behavior
The post would appear when searching (this is what occurs when using the database search instead of Bleve)

#### Observed behavior (that appears unintentional) 
The post doesn't appear in the search

**Comment by amyblais** [comment] 2023-06-09 18:38
Closing as a duplicate of https://github.com/mattermost/mattermost/issues/20531

**Closed by amyblais** 2023-06-09 18:38 UTC

**Comment by bryantgeorge** [comment] 2023-06-09 18:52
> Closing as a duplicate of #20531

Isn't this distinct from that issue because that one is referring to searching for text found within the attachment itself? I'm referring to the text of the post prior to the attachment (which is an issue specific to Bleve)

Makes sense that perhaps they are similar enough to be grouped/fixed together though
