### ISSUE TITLE
Official docker container - arm64 builds?

### ISSUE THREAD

**Issue by DanielHeath** [mattermost/mattermost#26440] opened 2024-03-11 22:28 UTC
https://hub.docker.com/r/mattermost/mattermost-team-edition provides a `linux/amd64` build, but no `linux/arm64` build. The rest of mattermost is built for arm as well, and arm CPUs are markedly cheaper to run.

**Comment by agnivade** [comment] 2024-03-12 07:46
Hey @DanielHeath - Currently we don't support ARM architectures. However, you are welcome to build and run it yourselves.

**Comment by amyblais** [comment] 2024-03-12 13:32
Closing as duplicate of https://github.com/mattermost/mattermost/issues/23387.

**Closed by amyblais** 2024-03-12 13:32 UTC
