### ISSUE TITLE
Typo in AddEmoji component

### ISSUE THREAD

**Issue by akbarkz** [mattermost/mattermost#25050] opened 2023-10-22 03:20 UTC
#### Summary
A small typo in text in AddEmoji component and its corresponding English translation

#### Expected behavior
The word should be "went" instead of "when" in "Something _when_ wrong when adding the custom emoji."

#### Observed behavior (that appears unintentional) 
<img width="601" alt="Screenshot 2023-10-22 at 09 15 18" src="https://github.com/mattermost/mattermost/assets/15943863/6d3f01d0-689a-4412-b23d-d9a48a50fbd5">

<img width="628" alt="Screenshot 2023-10-22 at 09 15 25" src="https://github.com/mattermost/mattermost/assets/15943863/ca637e06-95bf-4022-b8a8-2d8099d38e5f">

#### Possible fixes
webapp/channels/src/components/emoji/add_emoji/add_emoji.tsx#210
webapp/channels/src/i18n/en.json#113

**Comment by M-ZubairAhmed** [comment] 2023-10-22 10:20
@akbarkz thank you for reporting this

**Comment by obi-sammy** [comment] 2023-10-22 13:19
I noticed that someone had already tagged this issue to a PR about 4hrs ago and 3 hrs ago @M-ZubairAhmed added the help wanted tag to this issue, does this means that I can be assigned to this issue

**Comment by lalitkumawat1m** [comment] 2023-10-22 23:54
Hello team, I want to work on this issue please assign to me

**Comment by M-ZubairAhmed** [comment] 2023-10-23 06:55
@obi-sammy Thank you for the question. When we add `up for grabs` label, it signifies the issue is open to be worked upon.

**Comment by M-ZubairAhmed** [comment] 2023-10-23 06:58
@lalitkumawat1m the PR is already open. Can you please find another issue to work on ?

**Closed** 2023-10-24 06:19 UTC
Labels: Help Wanted, kind/bug
