### ISSUE TITLE
Wrong server update notification in system console

### ISSUE THREAD

**Issue by eli-yip** [mattermost/mattermost#28167] opened 2024-09-12 13:52 UTC
I have upgraded my team-edition server to 10.0.0. I know 10.0.0 has not been release yet, but release version(not rc version) has been cut out.

In my system `console`-`reporting`-`workspace optimization`, mm notices me that a major update is waiting for me: 9.11.1. It is obviously wrong.

Expected behavior: mattermost server should only check latest mirror update if current major version is still in support cycle. For example, 9.10.x should check for 9.10.y as 9.10 is still under maintenance. 10.0.0 should check for 10.x.x.

And more question: can I disable this update check? I can't find it in docs.

![2024-09-12-bw9YH41H001007](https://github.com/user-attachments/assets/369c8bb4-6639-411e-baea-c5680e399794)
![2024-09-12-1Arj9xuo001006](https://github.com/user-attachments/assets/dd4090b4-2a46-4740-bd99-7e8f7193ba5c)

**Comment by amyblais** [comment] 2024-09-12 14:41
Closing as duplicate of https://github.com/mattermost/mattermost/issues/28156.

**Closed by amyblais** 2024-09-12 14:41 UTC
