### ISSUE TITLE
Unable to write curly brackets or backslash with mac client anymore

### ISSUE THREAD

**Issue by zetaab** [mattermost/mattermost#22370] opened 2023-02-22 13:58 UTC
#### Summary

it seems that its impossible to write some characters anymore because these combinations are used for things like numbered list. 

![image](https://user-images.githubusercontent.com/22482503/220640751-e5fa8c3b-1f1d-4bbf-bb94-5d9bc69972a2.png)
<img width="407" alt="Screenshot 2023-02-22 at 15 57 35" src="https://user-images.githubusercontent.com/22482503/220641367-7290604b-f075-473a-b2d6-40f467d51c18.png">
<img width="332" alt="Screenshot 2023-02-22 at 16 03 00" src="https://user-images.githubusercontent.com/22482503/220643068-324655a6-7104-4e36-88fd-26fb4673c288.png">

#### Steps to reproduce

Try to write `{` or `\` or `}` in mattermost webapp using nordic keyboard layout (I am using finnish keyboard)
 
#### Expected behavior

Expected is that we could still write characters like `\` or `{` or `}`

#### Observed behavior (that appears unintentional) 

see summary

#### Possible fixes
change the keymapping

**Comment by bluebike** [comment] 2023-02-22 14:26
In Apple Mac Swedish/Finnish keyboard layout: 

⌥ (option) + 7 => "|"  
⌥ (option) + 8 => "[" 
⌥ (option) + 8 => "]"

⇧ (shift) + ⌥ (option) + 7 => "\\"  
⇧ (shift) + ⌥ (option) + 8 => "{" 
⇧ (shift) + ⌥ (option) + 8 => "}"

**Comment by amyblais** [comment] 2023-02-22 16:00
@zetaab What Mattermost server version are you on? What MacOS version are you on?

**Comment by amyblais** [comment] 2023-02-22 18:01
Opened https://mattermost.atlassian.net/browse/MM-50742.

**Comment by jby** [comment] 2023-08-31 09:40
@amyblais - your Jira ticket got closed as a duplicate and the one it's a duplicate off is closed as "Resolved - Won't do"
Does that mean you won't do anything about it? And - if so, why not?

**Comment by jby** [comment] 2023-08-31 09:49
Ok, so I did find #20530, but still - "Resolved - won't do"...

**Comment by amyblais** [comment] 2023-08-31 12:22
cc @Willyfrog @hmhealey Maybe you have more context on why the above tickets were closed.

**Comment by Willyfrog** [comment] 2023-08-31 13:13
Looks like a mistake from my side. I marked the duplicates and seems I closed both, while one should have remained open.

**Comment by Willyfrog** [comment] 2023-08-31 13:16
I have reopened it, thanks for flagging. Feel free to transition to the right state

**Comment by reftel** [comment] 2023-09-12 08:49
I can reproduce with a Norwegian keyboard on version 5.4.0 of the Mac client and the web interface of server version 7.8.9 (Webapp Build Hash: 65aaab5fbf802cd64b8093c1b180ee23593e0cc3)

**Comment by jby** [comment] 2023-09-15 14:21
One of my users commented on it internally:

> personally the preferred solution would have been a simple setting to "disable" the entire bottom row and get back to pure "markup" mode as it was before.  It is three lines instead of just 1 a it was a year or two ago

**Comment by PoC-dev** [comment] 2023-09-29 08:27
I can duplicate part of the issue with a German Keyboard running 12.7.
`⇧ (shift) + ⌥ (option) + 7` switches to kind of a numbered list thing instead of typing a literal backslash. I'm connecting to Server 8.1.2.

My current workaround is to have a backslash in the clipboard: Copy-Paste works.

**Closed** 2023-10-20 13:52 UTC
Labels: Up For Grabs, Help Wanted
