### ISSUE TITLE
Gitlab Authentication Fail - Bad response from token request

### ISSUE THREAD

**Issue by CodeMouse92** [mattermost/mattermost#25464] opened 2023-11-16 22:52 UTC
#### Summary
**NOT A DUPLICATE. Please read details carefully.**

I am using Mattermost 9.2.2 (Team Edition) on Ubuntu 22.04, installed according to your official documentation. I am running GitLab 16.5. Importantly, I have another application using OAuth 2.0 authentication against this same GitLab instance, with no problems.

When I set up GitLab Single Sign-On (as outlined [here](https://docs.mattermost.com/onboard/sso-gitlab.html#migrating-from-oauth-2-0-to-openid-connect)), it fails on the second stage of the OAuth process with "Bad response from token request."

I'm well familiar with OAuth2, so I logged the network calls with [F12] -> Network, and then successfully used the data in the responses from GitLab to acquire a valid access key, and the user data thereof, on the exact endpoints configured in Mattermost's configuration. However, Mattermost seems to be failing in validating the token somehow.

I have already applied the solutions outlined here, but the problem persists: https://mattermost.atlassian.net/browse/MM-42474

#### Steps to reproduce
* Ubuntu 22.04, recent installation, up-to-date.
* Mattermost 9.2.2 (Team Edition) installed from the official Mattermost Server PPA
* ServiceSettings SIteURL in Mattermost configuration is set to the https url for Mattermost.
* Scope is `read_user` on the GitLab Application configuration, and manually set in the Mattermost configuration as per above ticket.
* Added Discovery URL manually; confirmed it is working.
* GitLab Omnibus (16.5).
* Apache2 reverse proxy with SSL. Certificates confirmed valid.
* Confirmed all URLs for GitLab and Mattermost are working, both directly and via network traffic logging. All calls to either Mattermost or GitLab are over https, both in configuration and in practice.
* First step of OAuth process *succeeds*, indicating communication between Mattermost and GitLab.
* Second step of OAuth process *fails* when calling https://{mattermost_url}/signup/gitlab/complete

#### Expected behavior
Authentication should succeed.

#### Observed behavior (that appears unintentional) 
Fails with:

```
Error

Bad response from token request.
```

**Comment by amyblais** [comment] 2023-11-16 23:21
Hi @CodeMouse92,
1. Are you on webapp or desktop app?
2. Do you have any subpaths configured?
3. What Mattermost server version did you upgrade from?

**Comment by CodeMouse92** [comment] 2023-11-17 00:00
> 1. Are you on webapp or desktop app?

Web application.

> 2. Do you have any subpaths configured?

Not sure what you mean by this.

> 3. What Mattermost server version did you upgrade from?

I didn't. This is a completely fresh install.

**Comment by amyblais** [comment] 2023-11-17 16:11
Opened https://mattermost.atlassian.net/browse/MM-55597.

**Comment by CodeMouse92** [comment] 2023-11-29 19:21
From the Mattermost log:

```
{"timestamp":"2023-11-29 13:09:15.617 -06:00","level":"error","msg":"Bad response from token request.","caller":"web/context.go:115","path":"/signup/gitlab/complete","request_id":"ynyna6jypffcdjk17a61zjp7yy","ip_addr":"127.0.0.1","user_id":"","method":"GET","err_where":"AuthorizeOAuthUser","http_code":500,"error":"AuthorizeOAuthUser: Bad response from token request., response_body={\"error\":\"invalid_grant\",\"error_description\":\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"}, status_code=400, error=<nil>"}
```

Here's the exact network calls, with client ID, client secret, state, and code all scrubbed. As I scrubbed, I confirmed they were always the same.

* 200: `https://chat.mousepawmedia.com/oauth/gitlab/login`
* 200: `https://gitlab.mousepawmedia.com/oauth/authorize?response_type=code&client_id=CLIENTID&redirect_uri=https%3A%2F%2Fchat.mousepawmedia.com%2Fsignup%2Fgitlab%2Fcomplete&state=STATE&scope=read_user`
* 500: `https://chat.mousepawmedia.com/signup/gitlab/complete?code=CODE&state=STATE`

For good measure, here's the settings from the Application registered in GitLab (and I've confirmed the client ID and client secret):

* Callback URL:
  * `https://chat.mousepawmedia.com/login/gitlab/complete`
  * `https://chat.mousepawmedia.com/signup/gitlab/complete`
* Trusted 	Yes
* Confidential 	Yes
* Scopes 	
  * read_user (Read the authenticated user's personal information)

**Comment by phields** [comment] 2024-01-03 15:07
same problem here, I can login form the mattermost gitlab plugin, but not the gitlab SSO

**Comment by phields** [comment] 2024-01-03 23:02
I check the log on gitlab server:
`

{"method":"GET","path":"/oauth/authorize","format":"html","controller":"Oauth::AuthorizationsController","action":"new","status":200,"time":"2024-01-03T22:49:40.219Z","params":[{"key":"response_type","value":"code"},{"key":"client_id","value":"XF6I7dTWKqmHYX44GlPVDpLobupyG9TFfyAezRHJ8uU"},{"key":"redirect_uri","value":"[https://chat.mydomin.com/signup/gitlab/complete"},{"key":"state","value":"eyJhY3Rpb24iOiJsb2dpbiIsImlzTW9iaWxlIjoiZmFsc2UiLCJ0b2tlbiI6Im9mNnBvYXNyaW03ZDFyajVzdWFnYjNqY21xYWJhOGZzNXRpaWJqN204ZmVneXVwNXB1bWU5c2lwYTc2Zmo0M2kifQ=="},{"key":"scope","value":"api](https://chat.mydomin.com/signup/gitlab/complete%22%7D,%7B%22key%22:%22state%22,%22value%22:%22eyJhY3Rpb24iOiJsb2dpbiIsImlzTW9iaWxlIjoiZmFsc2UiLCJ0b2tlbiI6Im9mNnBvYXNyaW03ZDFyajVzdWFnYjNqY21xYWJhOGZzNXRpaWJqN204ZmVneXVwNXB1bWU5c2lwYTc2Zmo0M2kifQ==%22%7D,%7B%22key%22:%22scope%22,%22value%22:%22api) read_api read_user read_repository write_repository read_observability write_observability admin_mode openid profile email"}],"redis_calls":4,"redis_allowed_cross_slot_calls":1,"redis_duration_s":0.002663,"redis_read_bytes":181,"redis_write_bytes":1130,"redis_sessions_calls":3,"redis_sessions_allowed_cross_slot_calls":1,"redis_sessions_duration_s":0.002174,"redis_sessions_read_bytes":181,"redis_sessions_write_bytes":1077,"redis_shared_state_calls":1,"redis_shared_state_duration_s":0.000489,"redis_shared_state_write_bytes":53,"db_count":5,"db_write_count":1,"db_cached_count":1,"db_replica_count":0,"db_primary_count":5,"db_main_count":5,"db_main_replica_count":0,"db_replica_cached_count":0,"db_primary_cached_count":1,"db_main_cached_count":1,"db_main_replica_cached_count":0,"db_replica_wal_count":0,"db_primary_wal_count":0,"db_main_wal_count":0,"db_main_replica_wal_count":0,"db_replica_wal_cached_count":0,"db_primary_wal_cached_count":0,"db_main_wal_cached_count":0,"db_main_replica_wal_cached_count":0,"db_replica_duration_s":0.0,"db_primary_duration_s":0.004,"db_main_duration_s":0.004,"db_main_replica_duration_s":0.0,"cpu_s":0.082291,"mem_objects":8076,"mem_bytes":594664,"mem_mallocs":2208,"mem_total_bytes":917704,"pid":1896284,"worker_id":"puma_2","rate_limiting_gates":[],"correlation_id":"01HK8R9913RAHNVGX4DGBJXYRT","db_duration_s":0.00342,"view_duration_s":0.00135,"duration_s":0.05609}
{"method":"POST","path":"/oauth/token","format":"json","controller":"Oauth::TokensController","action":"create","status":400,"time":"2024-01-03T22:49:40.496Z","params":[{"key":"client_id","value":"XF6I7dTWKqmHYX44GlPVDpLobupyG9TFfyAezRHJ8uU"},{"key":"client_secret","value":"[FILTERED]"},{"key":"code","value":"[FILTERED]"},{"key":"grant_type","value":"authorization_code"},{"key":"redirect_uri","value":"[https://127.0.0.1:8065/signup/gitlab/complete"}],"db_count":2,"db_write_count":0,"db_cached_count":0,"db_replica_count":0,"db_primary_count":2,"db_main_count":2,"db_main_replica_count":0,"db_replica_cached_count":0,"db_primary_cached_count":0,"db_main_cached_count":0,"db_main_replica_cached_count":0,"db_replica_wal_count":0,"db_primary_wal_count":0,"db_main_wal_count":0,"db_main_replica_wal_count":0,"db_replica_wal_cached_count":0,"db_primary_wal_cached_count":0,"db_main_wal_cached_count":0,"db_main_replica_wal_cached_count":0,"db_replica_duration_s":0.0,"db_primary_duration_s":0.002,"db_main_duration_s":0.002,"db_main_replica_duration_s":0.0,"cpu_s":0.101158,"mem_objects":4176,"mem_bytes":328504,"mem_mallocs":1270,"mem_total_bytes":495544,"pid":1896284,"worker_id":"puma_2","rate_limiting_gates":[],"correlation_id":"01HK8R99981CPHF0EAZCKJCN9Y","db_duration_s":0.00155,"view_duration_s":0.00032,"duration_s":0.087](https://127.0.0.1:8065/signup/gitlab/complete%22%7D%5D,%22db_count%22:2,%22db_write_count%22:0,%22db_cached_count%22:0,%22db_replica_count%22:0,%22db_primary_count%22:2,%22db_main_count%22:2,%22db_main_replica_count%22:0,%22db_replica_cached_count%22:0,%22db_primary_cached_count%22:0,%22db_main_cached_count%22:0,%22db_main_replica_cached_count%22:0,%22db_replica_wal_count%22:0,%22db_primary_wal_count%22:0,%22db_main_wal_count%22:0,%22db_main_replica_wal_count%22:0,%22db_replica_wal_cached_count%22:0,%22db_primary_wal_cached_count%22:0,%22db_main_wal_cached_count%22:0,%22db_main_replica_wal_cached_count%22:0,%22db_replica_duration_s%22:0.0,%22db_primary_duration_s%22:0.002,%22db_main_duration_s%22:0.002,%22db_main_replica_duration_s%22:0.0,%22cpu_s%22:0.101158,%22mem_objects%22:4176,%22mem_bytes%22:328504,%22mem_mallocs%22:1270,%22mem_total_bytes%22:495544,%22pid%22:1896284,%22worker_id%22:%22puma_2%22,%22rate_limiting_gates%22:%5B%5D,%22correlation_id%22:%2201HK8R99981CPHF0EAZCKJCN9Y%22,%22db_duration_s%22:0.00155,%22view_duration_s%22:0.00032,%22duration_s%22:0.087)}
{"method":"GET","path":"/-/metrics","format":"html","controller":"MetricsController","action":"index","status":200,"time":"2024-01-03T22:49:53.508Z","params":[],"db_count":0,"db_write_count":0,"db_cached_count":0,"db_replica_count":0,"db_primary_count":0,"db_main_count":0,"db_main_replica_count":0,"db_replica_cached_count":0,"db_primary_cached_count":0,"db_main_cached_count":0,"db_main_replica_cached_count":0,"db_replica_wal_count":0,"db_primary_wal_count":0,"db_main_wal_count":0,"db_main_replica_wal_count":0,"db_replica_wal_cached_count":0,"db_primary_wal_cached_count":0,"db_main_wal_cached_count":0,"db_main_replica_wal_cached_count":0,"db_replica_duration_s":0.0,"db_primary_duration_s":0.0,"db_main_duration_s":0.0,"db_main_replica_duration_s":0.0,"cpu_s":0.230406,"mem_objects":2789,"mem_bytes":1736264,"mem_mallocs":9693,"mem_total_bytes":1847824,"pid":1896282,"worker_id":"puma_1","rate_limiting_gates":[],"correlation_id":"49a1086d-41a7-4d2b-b2e1-cc6453918363","db_duration_s":0.0,"view_duration_s":0.00103,"duration_s":0.22536}

`

**Comment by sbishel** [comment] 2024-02-05 20:52
We performed a triage initial investigation and a little bit more deep investigation on the potential problem and solution to this but were unable to duplicate.  I will post my notes below. 

Notes:
- previous similar issues were more related to redirect_uri protocol changed via load balancer modifying headers or SiteURL config value incorrectly set or missing. Nothing similar to this case in our solved ZD DB ticket list.
- redirect_uri seems correctly set.
- Quick code investiogation I found that: We check for an array of redirect URLs for their validity: https://github.com/mattermost/mattermost/blob/dfa476a6882373ba73b429fd9d9ea796de28bd41/model/oauth.go#L126 and Here we check the RedirectURL passed during OAuth or SAML https://github.com/mattermost/mattermost/blob/7c7c4716e6cc73878734f4b52a34800096bd39e7/utils/utils.go#L197

Potential Solutions:
-Maybe worth checking that the SiteUrl config match exactly with redirect_uri. Check protocol. 
-Also check that the value must exactly match one of the authorized redirect URIsfor the OAuth 2.0 client, which he should have configured already.
-Just in case try setting this config to false and try again: 

the important points is:
the client ID and redirect URI used in the authorization request are exactly as registered in GitLab.

the client ID and client secret are correctly used when making the token request to exchange the authorization code for an access token, and that this request also matches the redirect URI used initially.

**Comment by amyblais** [comment] 2024-02-29 21:16
Closing as a Help Wanted issue was opened for this,

**Closed by amyblais** 2024-02-29 21:16 UTC
Labels: Bug Report/Open

**Comment by CodeMouse92** [comment] 2024-03-29 20:42
@phields Are you willing to help with an odd angle to debugging this? Part of me wonders if there's something odd about GitLab that is causing this. I initially dismissed the possbility, because I have other OAuth2 authentication succeeding against my GitLab instance. However, I've now slammed into what seems to be the same issue with a self-hosted instance of [Taiga](https://taiga.io/). Since that's a pretty lightweight Docker app, can you fire it up and see if you can get OAuth2 authentication working against your GitLab instance? If _so_, then I'm probably sitting on a coincidence, but if_not_, then we may both be sitting on GitLab instances that have some odd bug with OAuth2, at which point, the problem isn't Mattermost.

Feel free to contact me via codemouse92 (at) out look with the outcome, and we can compare notes and see if we can track down enough information to either advance this help issue or to file a bug report with GitLab.

**Comment by xolyu** [comment] 2025-01-03 06:27
I had exactly the same behavior as @CodeMouse92 described [here](https://github.com/mattermost/mattermost/issues/25464#issuecomment-1832556567). The same log entries, also from Mattermost status code `500`, after the previous response from GitLab was status code `400`.  

Some logs of my problem:

<details><summary>Example log from Mattermost (Click to expand)</summary>

_I've added some line breaks for better reading._

```json
{
    "timestamp": "2025-01-02 06:11:50.959 +01:00",
    "level": "error",
    "msg": "Bad response from token request.",
    "caller": "web/context.go:124",
    "path": "/signup/gitlab/complete",
    "request_id": "6e5m5ouqepypmcadge4incz5sa",
    "ip_addr": "127.0.0.1",
    "user_id": "",
    "method": "GET",
    "err_where": "AuthorizeOAuthUser",
    "http_code": 500,
    "error": "AuthorizeOAuthUser: Bad response from token request.,
        response_body={
            \"error\":\"invalid_grant\",
            \"error_description\":\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"
        },
        status_code=400,
        error=<nil>
    "
}
```

</details>

<details><summary>Example log from GitLab (Click to expand)</summary>

```json
{
    "method": "POST",
    "path": "/oauth/authorize",
    "format": "html",
    "controller": "Oauth::AuthorizationsController",
    "action": "create",
    "status": 302,
    "location": "https://mattermost.k3web.app/signup/gitlab/complete",
    "time": "2025-01-02T06:13:44.522Z",
    "params": [
        {
            "key": "authenticity_token",
            "value": "[FILTERED]"
        },
        {
            "key": "client_id",
            "value": "56adeb1d...f4b4e9"
        },
        {
            "key": "redirect_uri",
            "value": "[FILTERED]"
        },
        {
            "key": "state",
            "value": "eyJhY3Rpb24iOiJsb2dpbiIsImlz...4ZmFtNjdqN3prNjkifQ=="
        },
        {
            "key": "response_type",
            "value": "code"
        },
        {
            "key": "scope",
            "value": "read_user"
        },
        {
            "key": "nonce",
            "value": ""
        },
        {
            "key": "code_challenge",
            "value": ""
        },
        {
            "key": "code_challenge_method",
            "value": ""
        }
    ],
    ...
}
{
    "method": "POST",
    "path": "/oauth/token",
    "format": "json",
    "controller": "Oauth::TokensController",
    "action": "create",
    "status": 400,
    "time": "2025-01-02T06:13:44.640Z",
    "params": [
        {
            "key": "client_id",
            "value": "56adeb1d...f4b4e9"
        },
        {
            "key": "client_secret",
            "value": "[FILTERED]"
        },
        {
            "key": "code",
            "value": "[FILTERED]"
        },
        {
            "key": "grant_type",
            "value": "authorization_code"
        },
        {
            "key": "redirect_uri",
            "value": "[FILTERED]"
        }
    ],
    "correlation_id": "01JGJTC10JVJQYYMWNAMCT1PGF",
    "remote_ip": "192.168.20.1",
    "ua": "Mattermost-Bot/1.1",
    ...
}
```

</details>


After a long search for the problem, I was able to narrow it down and fix it.

The Setup: Mattermost was installed in the Omnibus deployment method. In addition, an nginx is running as a reverse proxy with TLS termination in front of the services (GitLab and Mattermost).

Since Mattermost-Omnibus itself sets up an nginx with cache configuration on port `80`, I left it and configured the proxy_pass of my own Reverse Proxy to port `80`. Everything worked, Mattermost was accessible without any problems, except the functionality of GitLab-OAuth2.

After I left out the nginx configured by Mattermost-Omnibus and configured my reverse proxy to port `8056`, the signin via GitLab-OAuth2 suddenly worked without any problems. The nginx directly in front of Mattermost is now deactivated.

The working raw GitLabSettings in Mattermost looks like:
```json
{
  "Enable": true,
  "Secret": "********************************",
  "Id": "56adeb1d...f4b4e9",
  "Scope": "read_user",
  "AuthEndpoint": "https://<GitLab-Domain>/oauth/authorize",
  "TokenEndpoint": "https://<GitLab-Domain>/oauth/token",
  "UserAPIEndpoint": "https://<GitLab-Domain>/api/v4/user",
  "DiscoveryEndpoint": "",
  "ButtonText": "",
  "ButtonColor": ""
}
```

&rArr; So the solution for me is to access port `8056` from the Mattermost server directly from my reverse proxy (which does TLS termination). No other reverse proxy in between.

---

_I know the issue is already closed, I would like to document the solution to the problem for further searchers; because it cost me a lot of time and nerves altogether._
