### ISSUE TITLE
Expired GPG key

### ISSUE THREAD

**Issue by m1waterman88** [mattermost/mattermost#26717] opened 2024-04-08 14:31 UTC
#### Summary
The Mattermost GPG key expired on 2024-04-06.

#### Steps to reproduce
Run `sudo apt update` on Ubuntu 22.04 to find warnings

#### Expected behavior
I should be able to update the package cache and the package if applicable.

#### Observed behavior (that appears unintentional) 
I can't update the package cache or any applicable packages as the GPG key is expired.

```
Err:9 https://deb.packages.mattermost.com stable InRelease
  The following signatures were invalid: EXPKEYSIG F8F2C31744774B28 Mattermost Build <dev-ops@mattermost.com>
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.packages.mattermost.com stable InRelease: The following signatures were invalid: EXPKEYSIG F8F2C31744774B28 Mattermost Build <dev-ops@mattermost.com>
W: Failed to fetch https://deb.packages.mattermost.com/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG F8F2C31744774B28 Mattermost Build <dev-ops@mattermost.com>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

```
<REDACTED>:/etc/apt/sources.list.d$ sudo apt-key list
...
/etc/apt/trusted.gpg.d/mattermost.gpg
-------------------------------------
pub   rsa2048 2017-03-27 [SC] [expired: 2024-04-06]
      A1B3 1D46 F0F3 A10B 02CF  2D44 F8F2 C317 4477 4B28
uid           [ expired] Mattermost Build <dev-ops@mattermost.com>
```

```
<REDACTED>:/etc/apt/sources.list.d$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

#### Possible fixes
Provide a new GPG key.

**Comment by amyblais** [comment] 2024-04-08 14:32
Closing as a duplicate of https://github.com/mattermost/mattermost/issues/26707.

**Closed by amyblais** 2024-04-08 14:32 UTC
