### ISSUE TITLE
Notifications not working in web client on Mac

### ISSUE THREAD

**Issue by MJegorovas** [mattermost/mattermost#27534] opened 2024-07-03 15:14 UTC
#### Summary
Notifications not working or not working properly depending on the browser in web client on Mac
macOS: 14.4 (23E214)
Safari: Version 17.4 (19618.1.15.11.12)
Firefox: 127.0.2 (64-bit)
Mattermost:
Mattermost Version: 9.10.0
Database Schema Version: 121
Build Number: 9664905391
Database: postgres

#### Steps to reproduce
Enable notification permission in any browser on Mac and try to get notification to show

#### Expected behavior
Notifications show up in notification centre and play a sound

#### Observed behavior (that appears unintentional) 
Safari:
No notification in centre or sound.
Well, actually there are very rare occurrences that either notification played a sound or I even got a notification in notification centre, but it is extremely rare.
Firefox:
No notification in centre, but it does play sound every time.
Found out this is because notification settings were turned off for Firefox in system settings and after enabling them I got a bit different behaviour - now every time I got notification I would get 2 sounds: 1 by mattermost and 1 by default system but again, no notification in the centre.

#### Possible fixes
For Safari, my basic debugging showed that even after granting notification permission, the moment mattermost tries to send a notification and executes this [line](https://github.com/mattermost/mattermost/blob/90534b13cfd394936d14e659a390c971fd739164/webapp/channels/src/utils/notifications.ts#L70), it returns error `Notification prompting can only be done from a user gesture` so notification does not get sent. `Notification.permission` that is checked before returns granted, so I don't know why ask for permission again.

**Comment by amyblais** [comment] 2024-07-03 15:27
https://mattermost.atlassian.net/browse/MM-59315

**Comment by hmhealey** [comment] 2024-07-10 16:18
Thanks for the feedback, @MJegorovas! There's definitely a bunch of stuff we should look at here.

It sounds like there's a few different things going on here:

1. On Safari, we're failing to request the user's permission correctly. That should've been fixed in 9.10.0 by https://github.com/mattermost/mattermost/pull/26849 which would make it so that the user is prompted for permission before receiving a new message. Do you see the bar asking for that permission?

    If not, could you open a new tab, open the JS console, and check what the value of `Notification.permission` is?
    
2. On Firefox, the notification not appearing in the Notification Centre is an odd one. Looking at the code, I think the issue is actually because of some very old logic for automatically closing notifications back before that was controlled by the OS. We should be good to just remove that logic now.

3. On Firefox, I think the doubled up notification sound is a long-running UX issue. Firefox doesn't let us disable the system sound, so we'd have either have to have the user disable their OS notification sound manually or disable the MM notification sound.

---

@abhijit-singh Any suggestion on how we might fix the third one? To summarize the above, if you have desktop notification sounds enabled on Firefox on Mac, you head both the MM notification sound as well as one from MacOS

**Comment by hmhealey** [comment] 2024-07-10 18:29
Because I like linking things, here's a ticket for the second issue I listed above (https://mattermost.atlassian.net/browse/MM-59404) and for the third one (https://mattermost.atlassian.net/browse/MM-59403).

I need some more details on the first one before I can look at fixing it

**Comment by MJegorovas** [comment] 2024-07-11 06:48
> On Safari, we're failing to request the user's permission correctly. That should've been fixed in 9.10.0 by https://github.com/mattermost/mattermost/pull/26849 which would make it so that the user is prompted for permission before receiving a new message. Do you see the bar asking for that permission?

Yes I do, this is the behaviour after granting it. Had more comments, but I see that in the issue you've got everything figured out.

**Comment by hmhealey** [comment] 2024-07-11 19:04
Thanks for confirming. Given we're finding that there's more issues here than we'd expected, I'm glad that that seems to cover everything you saw on Safari 😅

**Comment by hmhealey** [comment] 2024-07-16 15:56
Okay, to summarize the issues reported here:
1. MM notification sounds overlapping OS ones (MM-59315) - This is not fixed yet, but we're talking to the UX team about how that should be handled in cases where we can't prevent the OS notification sound from playing.
2. Notifications not appearing in notification center (MM-59404) - This is fixed in v10.0 coming in September. The fix has already been deployed to https://community.mattermost.com.
3. Notifications not working in Safari (MM-59416) - This is fixed in v9.10.1 coming soon and v9.11 coming in August. This fix has also been deployed to our community server.

Because the more critical issues with notifications just not working have been fixed, I'm going to close this issue, but feel free to reopen this if those issues reoccur.

Thanks again for reporting this! We need to get someone on the team to use Safari as their regular browser so we can catch this sort of issue sooner

**Closed by hmhealey** 2024-07-16 15:56 UTC
Labels: Bug Report/Open
