### ISSUE TITLE
Upgrade to Enterprise form Free causes loss of plugins

### ISSUE THREAD

**Issue by frakman1** [mattermost/mattermost#16983] opened 2021-02-19 03:16 UTC
Mattermost Version: [5.31.0](https://github.com/mattermost/mattermost-docker/blob/2b12534f900f51a485c47bcd880a61df1b20beb7/app/Dockerfile#L5)

![image](https://user-images.githubusercontent.com/5826484/108453932-76658880-7239-11eb-82ef-9771b990f60b.png)

#### Summary
Upgrading to Enterprise version from System Console causes loss of plugins

#### Long Description
I installed MM using [this](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml) `docker-compose.yml` file with PortainerCE on my UNRAID server. My configuration is identical except for the host volume locations and web port mappings.

I then installed a bunch of plugins (github, gif,meme, jitsi, todo etc) after configuring my team and inviting a few users.
I wanted to try the `Incident Collaboration` plugin but saw that it required an Enterprise Version
I opened the System Console and clicked on the `Upgrde to Enterprise button`:
![image](https://user-images.githubusercontent.com/5826484/108451483-e58cae00-7234-11eb-9ac7-51fea406dc4c.png)
I installed the plugin and that seemed to work. I created a playbook etc
Later, when I tried to install the `Channel Export` plugin which also requires Enterprise license, I got this error:

![image](https://user-images.githubusercontent.com/5826484/108451775-68ae0400-7235-11eb-80f1-86fe5d34ac09.png)

 I checked the logs in docker's mattermost_app_1 container and found this:
```
{"level":"error","ts":1613664206.8584263,"caller":"mlog/log.go:229","msg":"Unable to move plugin from temporary directory to final destination. Another plugin may be using the same directory name.","path":"/api/v4/plugins/marketplace","request_id":"ncd9h619njf4dmobwsnbmwx8ey","ip_addr":"172.27.0.3","user_id":"46gef9hpofrb98q7pyp4u4nxpa","method":"POST","err_where":"installExtractedPlugin","http_code":500,"err_details":"destination already exists"}
```

I then checked the Plugins Marketplace and I no longer had any plugins:
![image](https://user-images.githubusercontent.com/5826484/108451850-84190f00-7235-11eb-98db-916e51f33bf5.png)

However, if I list the plugins folder, they are all there but with empty contents:

```
/mattermost/plugins # ls -lasth
total 0      
     0 drwxr--r--    1 mattermo mattermo      12 Feb 17 21:10 com.github.moussetc.mattermost.plugin.giphy
     0 drwxr--r--    1 mattermo mattermo      12 Feb 17 21:10 com.mattermost.nps
     0 drwxr--r--    1 mattermo mattermo      12 Feb 17 21:10 com.mattermost.plugin-channel-export
     0 drwxr--r--    1 mattermo mattermo      12 Feb 17 21:10 com.mattermost.plugin-incident-management
     0 drwxr--r--    1 mattermo mattermo      12 Feb 17 21:10 com.mattermost.plugin-todo
     0 drwxr--r--    1 mattermo mattermo      12 Feb 17 21:10 com.mattermost.welcomebot
     0 drwxr--r--    1 mattermo mattermo      12 Feb 17 21:10 com.nilsbrinkmann.icebreaker
     0 drwxr--r--    1 mattermo mattermo      12 Feb 17 21:10 github
     0 drwxr--r--    1 mattermo mattermo      12 Feb 17 21:10 jitsi
     0 drwxr--r--    1 mattermo mattermo      12 Feb 17 21:10 memes
     0 drwxrwxrwx    1 99       users        466 Feb 17 21:01 .
     0 drwxr-sr-x    1 mattermo mattermo     242 Feb 13 00:37 ..
/mattermost/plugins # 
```
```
mattermost # tree plugins/
plugins/
├── com.github.moussetc.mattermost.plugin.giphy
│   └── server
│       └── dist
├── com.mattermost.nps
│   └── server
│       └── dist
├── com.mattermost.plugin-channel-export
│   └── server
│       └── dist
├── com.mattermost.plugin-incident-management
│   └── server
│       └── dist
├── com.mattermost.plugin-todo
│   └── server
│       └── dist
├── com.mattermost.welcomebot
│   └── server
│       └── dist
├── com.nilsbrinkmann.icebreaker
│   └── server
│       └── dist
├── github
│   └── server
│       └── dist
├── jitsi
│   └── server
│       └── dist
└── memes
    └── server
        └── dist
```

I switched back to Free version from within System Console and it still shows (0) plugins installed.
I restarted the server and ran ` chown -R mattermost:mattermost /mattermost`   but still the Installed plugins tab shows as (0)

At this point no plugins worked:

1- I could non longer see any plugins on the WebUI or run them with slash commands
2- I could not  install them from the UI because it says the folder already exists

Finally, I was able to recover by stopping the server, deleting the contents of `plugins` and `client/plugins` and starting the server up again. I was about to re-install all the plugins from scratch again.
However, the folders magically re-populated and work now (except for jitsi plugin which complains about a missing App ID)

#### Expected behavior
I expect to be able to upgrade to Enterprise and not lose all plugins.

#### Question:
What is the difference between the files located in `/mattermost/client/plugins` and `/mattermost/plugins`. They seem similar but not identical

```
/ # ls -lasth /mattermost/plugins/ /mattermost/client/plugins/
/mattermost/client/plugins/:
total 0      
     0 drwxr-xr-x    1 mattermo mattermo     272 Feb 18 20:48 .
     0 drwxr--r--    1 mattermo mattermo      64 Feb 18 20:48 jitsi
     0 drwxr--r--    1 mattermo mattermo     100 Feb 18 20:48 zoom
     0 drwxr--r--    1 mattermo mattermo     136 Feb 18 20:05 com.mattermost.plugin-incident-management
     0 drwxr--r--    1 mattermo mattermo      90 Feb 18 19:51 com.mattermost.nps
     0 drwxr--r--    1 mattermo mattermo     106 Feb 18 19:51 com.mattermost.plugin-todo
     0 drwxr--r--    1 mattermo mattermo      66 Feb 18 19:51 github
     0 drwxr--r--    1 mattermo mattermo     126 Feb 18 19:51 com.mattermost.plugin-channel-export
     0 drwxr-xr-x    1 mattermo mattermo    4.3K Feb 13 00:37 ..

/mattermost/plugins/:
total 0      
     0 drwxr--r--    1 mattermo mattermo      78 Feb 18 20:37 zoom
     0 drwxr-xr-x    1 mattermo mattermo     392 Feb 18 20:37 .
     0 drwxr--r--    1 mattermo mattermo      78 Feb 18 20:11 jitsi
     0 drwxr--r--    1 mattermo mattermo      78 Feb 18 19:51 com.mattermost.nps
     0 drwxr--r--    1 mattermo mattermo      78 Feb 18 19:51 com.mattermost.plugin-todo
     0 drwxr--r--    1 mattermo mattermo      66 Feb 18 19:51 com.nilsbrinkmann.icebreaker
     0 drwxr--r--    1 mattermo mattermo      78 Feb 18 19:51 github
     0 drwxr--r--    1 mattermo mattermo      54 Feb 18 19:51 memes
     0 drwxr--r--    1 mattermo mattermo      66 Feb 18 19:51 com.github.moussetc.mattermost.plugin.giphy
     0 drwxr--r--    1 mattermo mattermo      90 Feb 18 19:51 com.mattermost.plugin-channel-export
     0 drwxr--r--    1 mattermo mattermo      54 Feb 18 19:51 com.mattermost.welcomebot
     0 drwxr-sr-x    1 mattermo mattermo     242 Feb 13 00:37 ..
```

**Comment by amyblais** [comment] 2021-02-19 13:58
@ahmaddanialmohd / @iomodo Would you be able to take a look at this?

**Comment by amyblais** [comment] 2021-02-24 13:54
@frakman1 Would you be open to posting about this in our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? Someone on our dev team or in the community may be able to help.

**Comment by frakman1** [comment] 2021-02-24 15:32
@amyblais I posted about it last week [here](https://community.mattermost.com/core/pl/8xpiykwjf7g6ipijbeh5x6m55o)
I didn't get any answer. I reached out to an admin and he suggested I open an issue here.

**Comment by ahmaddanialmohd** [comment] 2021-02-24 22:33
Hi, @frakman1 

I noticed that you mentioned that the issue is fixed (except for the Jitsi plugin) [here](https://community.mattermost.com/core/pl/fcwzcgrer3d3fgtcihmo31ec1e). Can I please confirm that the issue is fixed for good and what is the current problem with the Jitsi plugin specifically?

**Comment by frakman1** [comment] 2021-02-24 23:43
The Jitsi error was a mistake due to a configuration in the plugin that was later resolved. That can be ignored.

The error condition I ran into was resolved by deleting the plugins folders and restarting the server. That's just how I recovered from this _error_.

This Github issue is a report of a **bug** that wipes out the plugins after an upgrade to Enterprise and should be handled as such.

**Comment by mindthecap** [comment] 2021-04-01 05:29
I ran into the same bug. For me, it was as simple as chown the plugins directories mattermost/bin/plugins and mattermost/client/plugins with recursion flag. Don't know when exactly the ownership changed (i did upgrade aswell).

**Comment by amyblais** [comment] 2021-04-01 13:24
Created a ticket for investigation: https://mattermost.atlassian.net/browse/MM-34562

**Comment by d-huynh** [comment] 2022-02-23 15:12
Hi, I got similar problem while upgrading from 6.2 to 6.3.1 and then again from 6.3.1 to 6.4.0 on an Ubuntu VM, not docker.
We use the self-hosted free version.

Steps to reproduce:
1. Rename the old mattermost folder to mattermost-2022-02-23
2. Stop mattermost with systemctl
2. Download the new version and untar to mattermost
3. Use `rsync` to copy the folders from `mattermost-2022-02-23/plugins` and `mattermost-2022-02-23/client/plugins` to `mattermost`. The result looks like this:
```
$ sudo ls mattermost/plugins/ -l
total 24
drwxr--r-- 5 mattermost mattermost 4096 Feb 14 20:47 com.github.matterpoll.matterpoll
drwxr--r-- 5 mattermost mattermost 4096 Feb 14 20:47 com.github.moussetc.mattermost.plugin.giphy
drwxr--r-- 7 mattermost mattermost 4096 Feb 14 20:47 focalboard
drwxr--r-- 5 mattermost mattermost 4096 Feb 14 20:47 jira
drwxr--r-- 5 mattermost mattermost 4096 Feb 14 20:47 playbooks
drwxr--r-- 4 mattermost mattermost 4096 Feb 14 20:47 standup-raven
```
4. Restart mattermost with systemctl
5. Plugins folders gone, client/plugins stay though:
```
$ sudo ls mattermost/plugins/ -l
total 12
drwxr--r-- 7 mattermost mattermost 4096 Feb 23 16:02 focalboard
drwxr--r-- 5 mattermost mattermost 4096 Feb 23 16:02 jira
drwxr--r-- 5 mattermost mattermost 4096 Feb 23 16:02 playbooks
```

**Comment by amyblais** [comment] 2024-09-06 16:07
Closing some older issues, let us know if this still reproduces on the latest version,

**Closed by amyblais** 2024-09-06 16:07 UTC
Labels: Bug Report/Open
