### ISSUE TITLE
Broken link in application to integrations documentation.  [Minor]

### ISSUE THREAD

**Issue by digdilem** [mattermost/mattermost#24126] opened 2023-07-26 12:26 UTC
#### Summary
A link in the integrations page returns 404 when clicked. 

#### Steps to reproduce
Using version 8.0.0

In the client (desktop or web), click the 9-dots top left, then 
Integrations -> Incoming Webhooks. Click "Build Your Own" 

![image](https://github.com/mattermost/mattermost/assets/4052275/cb093431-e250-4074-b78b-5601849f1b9f)

This takes you to `https://developers.mattermost.com/integrate/admin-guide/admin-webhooks-incoming/`  (Plus some utm tracking codes as GET arguments, removed here in case they are personally identifiable. Same error returned with and without them so I don't believe they are critical for this report.

![image](https://github.com/mattermost/mattermost/assets/4052275/e74bfb21-c659-4136-93fa-3472612c64c8)

#### Expected behavior
The link should take you to the relevant url. 

Presumably this endpoint has changed and not been updated in the source, I imagine it's an easy fix.

**Comment by amyblais** [comment] 2023-07-26 17:39
@cwarnermm Do you know if this a case of a missing docs redirect, or something that should be fixed in-product?

**Comment by cwarnermm** [comment] 2023-07-26 18:30
@amyblais - I'm unable to reproduce this issue in either a self-hosted v8.x instance nor a Cloud instance last updated July 20th. When I click on the same link across those test instances, I'm taken to the correct page: https://developers.mattermost.com/integrate/webhooks/incoming/.

I've confirmed that the correct redirect URL is configured as the permanent link managed Marketing via their [master spreadsheet](https://docs.google.com/spreadsheets/d/1O601H_A0IM8pR3FOfue29_C8flGV7xK3ts-tJUVDHHg/edit#gid=0).

And I've confirmed that this specific URL was corrected for the v8.0 release as part of https://github.com/mattermost/mattermost/pull/23694. See line 63 in [this task spreadsheet](https://docs.google.com/spreadsheets/d/1Fo-VKT9mYhd8VUy9APM-e6zfHaAuIhXvU922imQFpys/edit#gid=0). 

I wonder if this might be an issue specific to a new v8 deployment, or related to an upgrade to v8 from a previous release.

**Comment by digdilem** [comment] 2023-07-26 20:21
Thank you for looking at this. Frustrating that it's not reproducible.

> or related to an upgrade to v8 from a previous release.

This specific self-hosted version is our test instance of Mattermost. It's an upgrade from 7.2.2 (I think) using the usual method as per the documentation.

**Comment by digdilem** [comment] 2023-07-26 20:27
It occurs to me that if anyone has access to the 404 logs on the documentation webserver, it might give an indication how many people are affected by this.   If that shows it's a lot, and it's easier to treat the symptom if the cause is difficult to confirm, then a serverside redirect could help?

**Comment by amyblais** [comment] 2023-07-26 20:46
I opened a ticket for investigation https://mattermost.atlassian.net/browse/MM-53828.

**Closed** 2023-08-28 22:18 UTC
Labels: Bug Report/Scheduled for Release
