### ISSUE TITLE
Icons in reactions popup are shown too small

### ISSUE THREAD

**Issue by AlexHaan-i** [mattermost/mattermost#29491] opened 2024-12-05 08:05 UTC
#### Summary
When I try to select a reaction (emoticon) to add to a post, the icons are small in the popup.

#### Steps to reproduce
Start adding a reaction (emoticon) to a post.
See the icons in the popup.

#### Operating System
Ubuntu Linux 22.04 LTS x64, using Firefox 133.0.

#### Mattermost Server Version
Mattermost Team Edition
Mattermost Version: 10.1.2

#### Expected behavior
Icons are shown at a decent size.

#### Observed behavior
Icons are shown pretty small.
Custom icons do have a normal size.

#### Log Output
-

#### Additional Information
![Screenshot from 2024-12-05 09-00-10](https://github.com/user-attachments/assets/bd30e73a-b3bc-40ae-b09f-be27e2698dfc)

#### Possible fixes
-

**Comment by amyblais** [comment] 2024-12-05 08:25
Closing as a duplicate of https://github.com/mattermost/mattermost/issues/29114.

**Closed by amyblais** 2024-12-05 08:25 UTC

**Comment by AlexHaan-i** [comment] 2024-12-05 08:34
Ah, thank you. I searched for 'reaction' and didn't find that issue.
