### ISSUE TITLE
iOS Photo Upload Fails

### ISSUE THREAD

**Issue by JustinBack** [mattermost/mattermost#25652] opened 2023-12-06 14:20 UTC
#### Summary
It seems Mattermost is not able to process DNG files (in the App on iOS they display fine until app restart), then its a blank file.

#### Steps to reproduce
1. Take a RAW Photo on iOS
2. Upload to Mattermost
3. Restart Mattermost or access on another device to see the missing image

#### Expected behavior
Proper Image in the History

#### Technical Info

Mattermost Version: 9.2.3
Virtualization: Docker
iOS Version: 2.10.1
MacOS Sonoma 14.1.2 (Applies to both web and desktop version)

#### Observed behavior (that appears unintentional) 
```
generateMiniPreview: prepareImage failed error=prepareImage: failed to decode image: imaging: failed to decode image: tiff: unsupported feature: color model 
```
![image](https://github.com/mattermost/mattermost/assets/40178814/03cdbf80-e9ea-4241-8019-aa8de6f0cfd2)

#### Possible fixes
N/A

**Comment by amyblais** [comment] 2023-12-06 15:38
Hi @JustinBack,
1. What Mattermost server version are you on?
2. What Mattermost mobile app version are you on?
3. What OS version are you on?
4. Are you able to reproduce this issue on our community server https://community.mattermost.com/?

**Comment by JustinBack** [comment] 2023-12-06 15:40
> Hi @JustinBack,
> 
> 1. What Mattermost server version are you on?
> 2. What Mattermost mobile app version are you on?
> 3. What OS version are you on?
> 4. Are you able to reproduce this issue on our community server https://community.mattermost.com/?

Argh forgot to include it, thanks! Its now in the original issue.

**Comment by hmhealey** [comment] 2023-12-11 14:28
Looks like this is the same issue from https://github.com/golang/go/issues/57746

**Comment by JustinBack** [comment] 2023-12-11 14:34
Yep, seems to be an upstream issue of https://pkg.go.dev/golang.org/x/image/tiff go's implementation, at least according to the linked issue

**Comment by harshilsharma63** [comment] 2023-12-13 13:29
@JustinBack so considering browsers and many OSs don't support DNG and other RAW formats like Nikon's NEF and Cannon's CR2, we think its best if we attached raw images as generic files instead of trying to interpret them as images. Because these raw formats keep changing over time with release of new cameras and supporting tons of camera manufacturers, its also not feasible to support rendering them for preview purposes and allowing to download the original file.

Thoughts?

**Comment by JustinBack** [comment] 2023-12-13 13:47
Yeah that's the most reasonable way, as other apps do this as well. Much better approach than a broken image

**Comment by marianunez** [comment] 2024-05-20 13:29
Closing in favor of  https://github.com/mattermost/mattermost/issues/26965

**Closed by marianunez** 2024-05-20 13:29 UTC
Labels: Bug Report/Open
