### ISSUE TITLE
Sync `lang` property on `<html>` tag at `root.html`

### ISSUE THREAD

**Issue by Sn-Kinos** [mattermost/mattermost#27139] opened 2024-05-24 04:28 UTC
#### Summary
`lang` property is fixed with `en`.

#### Steps to reproduce
None

#### Expected behavior
It will be matched with `DefaultServerLocale` or `DefaultClientLocale`.

#### Observed behavior (that appears unintentional) 
It always fixed with `en`.
https://github.com/mattermost/mattermost/blob/50ac6fc0b520f57d46d9d8e2ad467410cb837970/webapp/channels/src/root.html#L2

#### Possible fixes
- Remove `lang="en" or change it when `window.onload`

**Comment by amyblais** [comment] 2024-05-24 13:32
Closing as a duplicate of https://github.com/mattermost/mattermost/issues/26672.

**Closed by amyblais** 2024-05-24 13:32 UTC
