### ISSUE TITLE
System console disappears due to misuse

### ISSUE THREAD

**Issue by ForcemCS** [mattermost/mattermost#25592] opened 2023-12-01 07:02 UTC
I'm testing this command in order to test 'curl -X POST -H 'Content-type: application/json' -H 'Authorisation: Bearer 'xxxxxxx --data '{"channel": "#alerts", "text": "hello world"} ' xxxxxxx:8065/api/v4/chat.postMessage '(don't really know if this is correct)
The first time I made a configuration change to my user (wukui), system console, and then the second time I logged in I found that the system console didn't exist anymore!

**Comment by ForcemCS** [comment] 2023-12-02 06:53
Version: 9.1.1
OS Ubuntu22.04

**Comment by amyblais** [comment] 2023-12-05 15:33
Opened https://mattermost.atlassian.net/browse/MM-56046.

**Comment by amyblais** [comment] 2023-12-14 14:05
Hi @ForcemCS, we couldn't verify this on our end because the reproduction steps are not clear. The command ``/api/v4/chat.postMessage`` doesn't seem to exist. Would you be able to help provide clearer reproduction steps?

**Comment by amyblais** [comment] 2024-01-02 14:46
Closing for now until we receive clearer reproduction steps,

**Closed by amyblais** 2024-01-02 14:46 UTC
Labels: Awaiting Submitter Action
